// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockratelimit

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLimiter creates a new instance of MockLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLimiter {
	mock := &MockLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLimiter is an autogenerated mock type for the Limiter type
type MockLimiter struct {
	mock.Mock
}

type MockLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLimiter) EXPECT() *MockLimiter_Expecter {
	return &MockLimiter_Expecter{mock: &_m.Mock}
}

// AllowBulk provides a mock function for the type MockLimiter
func (_mock *MockLimiter) AllowBulk(ctx context.Context, institutionID string, cost int) error {
	ret := _mock.Called(ctx, institutionID, cost)

	if len(ret) == 0 {
		panic("no return value specified for AllowBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = returnFunc(ctx, institutionID, cost)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLimiter_AllowBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllowBulk'
type MockLimiter_AllowBulk_Call struct {
	*mock.Call
}

// AllowBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - institutionID string
//   - cost int
func (_e *MockLimiter_Expecter) AllowBulk(ctx interface{}, institutionID interface{}, cost interface{}) *MockLimiter_AllowBulk_Call {
	return &MockLimiter_AllowBulk_Call{Call: _e.mock.On("AllowBulk", ctx, institutionID, cost)}
}

func (_c *MockLimiter_AllowBulk_Call) Run(run func(ctx context.Context, institutionID string, cost int)) *MockLimiter_AllowBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLimiter_AllowBulk_Call) Return(err error) *MockLimiter_AllowBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLimiter_AllowBulk_Call) RunAndReturn(run func(ctx context.Context, institutionID string, cost int) error) *MockLimiter_AllowBulk_Call {
	_c.Call.Return(run)
	return _c
}

// AllowQuery provides a mock function for the type MockLimiter
func (_mock *MockLimiter) AllowQuery(ctx context.Context, institutionID string) error {
	ret := _mock.Called(ctx, institutionID)

	if len(ret) == 0 {
		panic("no return value specified for AllowQuery")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, institutionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLimiter_AllowQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllowQuery'
type MockLimiter_AllowQuery_Call struct {
	*mock.Call
}

// AllowQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - institutionID string
func (_e *MockLimiter_Expecter) AllowQuery(ctx interface{}, institutionID interface{}) *MockLimiter_AllowQuery_Call {
	return &MockLimiter_AllowQuery_Call{Call: _e.mock.On("AllowQuery", ctx, institutionID)}
}

func (_c *MockLimiter_AllowQuery_Call) Run(run func(ctx context.Context, institutionID string)) *MockLimiter_AllowQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLimiter_AllowQuery_Call) Return(err error) *MockLimiter_AllowQuery_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLimiter_AllowQuery_Call) RunAndReturn(run func(ctx context.Context, institutionID string) error) *MockLimiter_AllowQuery_Call {
	_c.Call.Return(run)
	return _c
}
