// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksriracha

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	sriracha "go.sriracha.dev/sriracha"
)

// MockTokenIndexer is an autogenerated mock type for the TokenIndexer type
type MockTokenIndexer struct {
	mock.Mock
}

type MockTokenIndexer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenIndexer) EXPECT() *MockTokenIndexer_Expecter {
	return &MockTokenIndexer_Expecter{mock: &_m.Mock}
}

// Match provides a mock function with given fields: ctx, tr, cfg
func (_m *MockTokenIndexer) Match(ctx context.Context, tr sriracha.TokenRecord, cfg sriracha.MatchConfig) ([]sriracha.Candidate, error) {
	ret := _m.Called(ctx, tr, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Match")
	}

	var r0 []sriracha.Candidate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sriracha.TokenRecord, sriracha.MatchConfig) ([]sriracha.Candidate, error)); ok {
		return rf(ctx, tr, cfg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sriracha.TokenRecord, sriracha.MatchConfig) []sriracha.Candidate); ok {
		r0 = rf(ctx, tr, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sriracha.Candidate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sriracha.TokenRecord, sriracha.MatchConfig) error); ok {
		r1 = rf(ctx, tr, cfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenIndexer_Match_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Match'
type MockTokenIndexer_Match_Call struct {
	*mock.Call
}

// Match is a helper method to define mock.On call
//   - ctx context.Context
//   - tr sriracha.TokenRecord
//   - cfg sriracha.MatchConfig
func (_e *MockTokenIndexer_Expecter) Match(ctx interface{}, tr interface{}, cfg interface{}) *MockTokenIndexer_Match_Call {
	return &MockTokenIndexer_Match_Call{Call: _e.mock.On("Match", ctx, tr, cfg)}
}

func (_c *MockTokenIndexer_Match_Call) Run(run func(ctx context.Context, tr sriracha.TokenRecord, cfg sriracha.MatchConfig)) *MockTokenIndexer_Match_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sriracha.TokenRecord), args[2].(sriracha.MatchConfig))
	})
	return _c
}

func (_c *MockTokenIndexer_Match_Call) Return(_a0 []sriracha.Candidate, _a1 error) *MockTokenIndexer_Match_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenIndexer_Match_Call) RunAndReturn(run func(context.Context, sriracha.TokenRecord, sriracha.MatchConfig) ([]sriracha.Candidate, error)) *MockTokenIndexer_Match_Call {
	_c.Call.Return(run)
	return _c
}

// Rebuild provides a mock function with given fields: ctx, src
func (_m *MockTokenIndexer) Rebuild(ctx context.Context, src sriracha.RecordSource) error {
	ret := _m.Called(ctx, src)

	if len(ret) == 0 {
		panic("no return value specified for Rebuild")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sriracha.RecordSource) error); ok {
		r0 = rf(ctx, src)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenIndexer_Rebuild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rebuild'
type MockTokenIndexer_Rebuild_Call struct {
	*mock.Call
}

// Rebuild is a helper method to define mock.On call
//   - ctx context.Context
//   - src sriracha.RecordSource
func (_e *MockTokenIndexer_Expecter) Rebuild(ctx interface{}, src interface{}) *MockTokenIndexer_Rebuild_Call {
	return &MockTokenIndexer_Rebuild_Call{Call: _e.mock.On("Rebuild", ctx, src)}
}

func (_c *MockTokenIndexer_Rebuild_Call) Run(run func(ctx context.Context, src sriracha.RecordSource)) *MockTokenIndexer_Rebuild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sriracha.RecordSource))
	})
	return _c
}

func (_c *MockTokenIndexer_Rebuild_Call) Return(_a0 error) *MockTokenIndexer_Rebuild_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenIndexer_Rebuild_Call) RunAndReturn(run func(context.Context, sriracha.RecordSource) error) *MockTokenIndexer_Rebuild_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function with no fields
func (_m *MockTokenIndexer) Stats() sriracha.IndexStats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 sriracha.IndexStats
	if rf, ok := ret.Get(0).(func() sriracha.IndexStats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(sriracha.IndexStats)
	}

	return r0
}

// MockTokenIndexer_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockTokenIndexer_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockTokenIndexer_Expecter) Stats() *MockTokenIndexer_Stats_Call {
	return &MockTokenIndexer_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockTokenIndexer_Stats_Call) Run(run func()) *MockTokenIndexer_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenIndexer_Stats_Call) Return(_a0 sriracha.IndexStats) *MockTokenIndexer_Stats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenIndexer_Stats_Call) RunAndReturn(run func() sriracha.IndexStats) *MockTokenIndexer_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function with given fields: ctx, src
func (_m *MockTokenIndexer) Sync(ctx context.Context, src sriracha.IncrementalRecordSource) error {
	ret := _m.Called(ctx, src)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sriracha.IncrementalRecordSource) error); ok {
		r0 = rf(ctx, src)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenIndexer_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockTokenIndexer_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - ctx context.Context
//   - src sriracha.IncrementalRecordSource
func (_e *MockTokenIndexer_Expecter) Sync(ctx interface{}, src interface{}) *MockTokenIndexer_Sync_Call {
	return &MockTokenIndexer_Sync_Call{Call: _e.mock.On("Sync", ctx, src)}
}

func (_c *MockTokenIndexer_Sync_Call) Run(run func(ctx context.Context, src sriracha.IncrementalRecordSource)) *MockTokenIndexer_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sriracha.IncrementalRecordSource))
	})
	return _c
}

func (_c *MockTokenIndexer_Sync_Call) Return(_a0 error) *MockTokenIndexer_Sync_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenIndexer_Sync_Call) RunAndReturn(run func(context.Context, sriracha.IncrementalRecordSource) error) *MockTokenIndexer_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenIndexer creates a new instance of MockTokenIndexer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenIndexer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenIndexer {
	mock := &MockTokenIndexer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
