// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksriracha

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	sriracha "go.sriracha.dev/sriracha"
)

// MockIncrementalRecordSource is an autogenerated mock type for the IncrementalRecordSource type
type MockIncrementalRecordSource struct {
	mock.Mock
}

type MockIncrementalRecordSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIncrementalRecordSource) EXPECT() *MockIncrementalRecordSource_Expecter {
	return &MockIncrementalRecordSource_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function with given fields: ctx, id
func (_m *MockIncrementalRecordSource) Fetch(ctx context.Context, id string) (sriracha.RawRecord, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 sriracha.RawRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sriracha.RawRecord, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sriracha.RawRecord); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sriracha.RawRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIncrementalRecordSource_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockIncrementalRecordSource_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIncrementalRecordSource_Expecter) Fetch(ctx interface{}, id interface{}) *MockIncrementalRecordSource_Fetch_Call {
	return &MockIncrementalRecordSource_Fetch_Call{Call: _e.mock.On("Fetch", ctx, id)}
}

func (_c *MockIncrementalRecordSource_Fetch_Call) Run(run func(ctx context.Context, id string)) *MockIncrementalRecordSource_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIncrementalRecordSource_Fetch_Call) Return(_a0 sriracha.RawRecord, _a1 error) *MockIncrementalRecordSource_Fetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIncrementalRecordSource_Fetch_Call) RunAndReturn(run func(context.Context, string) (sriracha.RawRecord, error)) *MockIncrementalRecordSource_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function with given fields: ctx, fn
func (_m *MockIncrementalRecordSource) Scan(ctx context.Context, fn func(string, sriracha.RawRecord) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(string, sriracha.RawRecord) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIncrementalRecordSource_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockIncrementalRecordSource_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(string , sriracha.RawRecord) error
func (_e *MockIncrementalRecordSource_Expecter) Scan(ctx interface{}, fn interface{}) *MockIncrementalRecordSource_Scan_Call {
	return &MockIncrementalRecordSource_Scan_Call{Call: _e.mock.On("Scan", ctx, fn)}
}

func (_c *MockIncrementalRecordSource_Scan_Call) Run(run func(ctx context.Context, fn func(string, sriracha.RawRecord) error)) *MockIncrementalRecordSource_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(string, sriracha.RawRecord) error))
	})
	return _c
}

func (_c *MockIncrementalRecordSource_Scan_Call) Return(_a0 error) *MockIncrementalRecordSource_Scan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIncrementalRecordSource_Scan_Call) RunAndReturn(run func(context.Context, func(string, sriracha.RawRecord) error) error) *MockIncrementalRecordSource_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// ScanSince provides a mock function with given fields: ctx, checkpoint, fn
func (_m *MockIncrementalRecordSource) ScanSince(ctx context.Context, checkpoint string, fn func(string, sriracha.RawRecord) error) error {
	ret := _m.Called(ctx, checkpoint, fn)

	if len(ret) == 0 {
		panic("no return value specified for ScanSince")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, func(string, sriracha.RawRecord) error) error); ok {
		r0 = rf(ctx, checkpoint, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIncrementalRecordSource_ScanSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScanSince'
type MockIncrementalRecordSource_ScanSince_Call struct {
	*mock.Call
}

// ScanSince is a helper method to define mock.On call
//   - ctx context.Context
//   - checkpoint string
//   - fn func(string , sriracha.RawRecord) error
func (_e *MockIncrementalRecordSource_Expecter) ScanSince(ctx interface{}, checkpoint interface{}, fn interface{}) *MockIncrementalRecordSource_ScanSince_Call {
	return &MockIncrementalRecordSource_ScanSince_Call{Call: _e.mock.On("ScanSince", ctx, checkpoint, fn)}
}

func (_c *MockIncrementalRecordSource_ScanSince_Call) Run(run func(ctx context.Context, checkpoint string, fn func(string, sriracha.RawRecord) error)) *MockIncrementalRecordSource_ScanSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(func(string, sriracha.RawRecord) error))
	})
	return _c
}

func (_c *MockIncrementalRecordSource_ScanSince_Call) Return(_a0 error) *MockIncrementalRecordSource_ScanSince_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIncrementalRecordSource_ScanSince_Call) RunAndReturn(run func(context.Context, string, func(string, sriracha.RawRecord) error) error) *MockIncrementalRecordSource_ScanSince_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIncrementalRecordSource creates a new instance of MockIncrementalRecordSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIncrementalRecordSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIncrementalRecordSource {
	mock := &MockIncrementalRecordSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
