// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksriracha

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAuditLog is an autogenerated mock type for the AuditLog type
type MockAuditLog struct {
	mock.Mock
}

type MockAuditLog_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditLog) EXPECT() *MockAuditLog_Expecter {
	return &MockAuditLog_Expecter{mock: &_m.Mock}
}

// Append provides a mock function with given fields: ctx, event, metadata
func (_m *MockAuditLog) Append(ctx context.Context, event string, metadata map[string]string) error {
	ret := _m.Called(ctx, event, metadata)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) error); ok {
		r0 = rf(ctx, event, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuditLog_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockAuditLog_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - event string
//   - metadata map[string]string
func (_e *MockAuditLog_Expecter) Append(ctx interface{}, event interface{}, metadata interface{}) *MockAuditLog_Append_Call {
	return &MockAuditLog_Append_Call{Call: _e.mock.On("Append", ctx, event, metadata)}
}

func (_c *MockAuditLog_Append_Call) Run(run func(ctx context.Context, event string, metadata map[string]string)) *MockAuditLog_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]string))
	})
	return _c
}

func (_c *MockAuditLog_Append_Call) Return(_a0 error) *MockAuditLog_Append_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuditLog_Append_Call) RunAndReturn(run func(context.Context, string, map[string]string) error) *MockAuditLog_Append_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: ctx
func (_m *MockAuditLog) Verify(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuditLog_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockAuditLog_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuditLog_Expecter) Verify(ctx interface{}) *MockAuditLog_Verify_Call {
	return &MockAuditLog_Verify_Call{Call: _e.mock.On("Verify", ctx)}
}

func (_c *MockAuditLog_Verify_Call) Run(run func(ctx context.Context)) *MockAuditLog_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAuditLog_Verify_Call) Return(_a0 error) *MockAuditLog_Verify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuditLog_Verify_Call) RunAndReturn(run func(context.Context) error) *MockAuditLog_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditLog creates a new instance of MockAuditLog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditLog(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditLog {
	mock := &MockAuditLog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
