// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksriracha

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIndexStorage is an autogenerated mock type for the IndexStorage type
type MockIndexStorage struct {
	mock.Mock
}

type MockIndexStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIndexStorage) EXPECT() *MockIndexStorage_Expecter {
	return &MockIndexStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, key
func (_m *MockIndexStorage) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIndexStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIndexStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockIndexStorage_Expecter) Delete(ctx interface{}, key interface{}) *MockIndexStorage_Delete_Call {
	return &MockIndexStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockIndexStorage_Delete_Call) Run(run func(ctx context.Context, key string)) *MockIndexStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIndexStorage_Delete_Call) Return(_a0 error) *MockIndexStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIndexStorage_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockIndexStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockIndexStorage) Get(ctx context.Context, key string) ([]byte, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIndexStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIndexStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockIndexStorage_Expecter) Get(ctx interface{}, key interface{}) *MockIndexStorage_Get_Call {
	return &MockIndexStorage_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockIndexStorage_Get_Call) Run(run func(ctx context.Context, key string)) *MockIndexStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIndexStorage_Get_Call) Return(_a0 []byte, _a1 error) *MockIndexStorage_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIndexStorage_Get_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockIndexStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// LoadCheckpoint provides a mock function with given fields: ctx
func (_m *MockIndexStorage) LoadCheckpoint(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadCheckpoint")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIndexStorage_LoadCheckpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadCheckpoint'
type MockIndexStorage_LoadCheckpoint_Call struct {
	*mock.Call
}

// LoadCheckpoint is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIndexStorage_Expecter) LoadCheckpoint(ctx interface{}) *MockIndexStorage_LoadCheckpoint_Call {
	return &MockIndexStorage_LoadCheckpoint_Call{Call: _e.mock.On("LoadCheckpoint", ctx)}
}

func (_c *MockIndexStorage_LoadCheckpoint_Call) Run(run func(ctx context.Context)) *MockIndexStorage_LoadCheckpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIndexStorage_LoadCheckpoint_Call) Return(_a0 string, _a1 error) *MockIndexStorage_LoadCheckpoint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIndexStorage_LoadCheckpoint_Call) RunAndReturn(run func(context.Context) (string, error)) *MockIndexStorage_LoadCheckpoint_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: ctx, key, value
func (_m *MockIndexStorage) Put(ctx context.Context, key string, value []byte) error {
	ret := _m.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIndexStorage_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockIndexStorage_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value []byte
func (_e *MockIndexStorage_Expecter) Put(ctx interface{}, key interface{}, value interface{}) *MockIndexStorage_Put_Call {
	return &MockIndexStorage_Put_Call{Call: _e.mock.On("Put", ctx, key, value)}
}

func (_c *MockIndexStorage_Put_Call) Run(run func(ctx context.Context, key string, value []byte)) *MockIndexStorage_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockIndexStorage_Put_Call) Return(_a0 error) *MockIndexStorage_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIndexStorage_Put_Call) RunAndReturn(run func(context.Context, string, []byte) error) *MockIndexStorage_Put_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCheckpoint provides a mock function with given fields: ctx, token
func (_m *MockIndexStorage) SaveCheckpoint(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for SaveCheckpoint")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIndexStorage_SaveCheckpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCheckpoint'
type MockIndexStorage_SaveCheckpoint_Call struct {
	*mock.Call
}

// SaveCheckpoint is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockIndexStorage_Expecter) SaveCheckpoint(ctx interface{}, token interface{}) *MockIndexStorage_SaveCheckpoint_Call {
	return &MockIndexStorage_SaveCheckpoint_Call{Call: _e.mock.On("SaveCheckpoint", ctx, token)}
}

func (_c *MockIndexStorage_SaveCheckpoint_Call) Run(run func(ctx context.Context, token string)) *MockIndexStorage_SaveCheckpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIndexStorage_SaveCheckpoint_Call) Return(_a0 error) *MockIndexStorage_SaveCheckpoint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIndexStorage_SaveCheckpoint_Call) RunAndReturn(run func(context.Context, string) error) *MockIndexStorage_SaveCheckpoint_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function with given fields: ctx, prefix, fn
func (_m *MockIndexStorage) Scan(ctx context.Context, prefix string, fn func(string, []byte) error) error {
	ret := _m.Called(ctx, prefix, fn)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, func(string, []byte) error) error); ok {
		r0 = rf(ctx, prefix, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIndexStorage_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockIndexStorage_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
//   - fn func(string , []byte) error
func (_e *MockIndexStorage_Expecter) Scan(ctx interface{}, prefix interface{}, fn interface{}) *MockIndexStorage_Scan_Call {
	return &MockIndexStorage_Scan_Call{Call: _e.mock.On("Scan", ctx, prefix, fn)}
}

func (_c *MockIndexStorage_Scan_Call) Run(run func(ctx context.Context, prefix string, fn func(string, []byte) error)) *MockIndexStorage_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(func(string, []byte) error))
	})
	return _c
}

func (_c *MockIndexStorage_Scan_Call) Return(_a0 error) *MockIndexStorage_Scan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIndexStorage_Scan_Call) RunAndReturn(run func(context.Context, string, func(string, []byte) error) error) *MockIndexStorage_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIndexStorage creates a new instance of MockIndexStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIndexStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIndexStorage {
	mock := &MockIndexStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
