// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksriracha

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	sriracha "go.sriracha.dev/sriracha"
)

// MockRecordSource is an autogenerated mock type for the RecordSource type
type MockRecordSource struct {
	mock.Mock
}

type MockRecordSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecordSource) EXPECT() *MockRecordSource_Expecter {
	return &MockRecordSource_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function with given fields: ctx, id
func (_m *MockRecordSource) Fetch(ctx context.Context, id string) (sriracha.RawRecord, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 sriracha.RawRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sriracha.RawRecord, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sriracha.RawRecord); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sriracha.RawRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRecordSource_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockRecordSource_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRecordSource_Expecter) Fetch(ctx interface{}, id interface{}) *MockRecordSource_Fetch_Call {
	return &MockRecordSource_Fetch_Call{Call: _e.mock.On("Fetch", ctx, id)}
}

func (_c *MockRecordSource_Fetch_Call) Run(run func(ctx context.Context, id string)) *MockRecordSource_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRecordSource_Fetch_Call) Return(_a0 sriracha.RawRecord, _a1 error) *MockRecordSource_Fetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRecordSource_Fetch_Call) RunAndReturn(run func(context.Context, string) (sriracha.RawRecord, error)) *MockRecordSource_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function with given fields: ctx, fn
func (_m *MockRecordSource) Scan(ctx context.Context, fn func(string, sriracha.RawRecord) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(string, sriracha.RawRecord) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRecordSource_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockRecordSource_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(string , sriracha.RawRecord) error
func (_e *MockRecordSource_Expecter) Scan(ctx interface{}, fn interface{}) *MockRecordSource_Scan_Call {
	return &MockRecordSource_Scan_Call{Call: _e.mock.On("Scan", ctx, fn)}
}

func (_c *MockRecordSource_Scan_Call) Run(run func(ctx context.Context, fn func(string, sriracha.RawRecord) error)) *MockRecordSource_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(string, sriracha.RawRecord) error))
	})
	return _c
}

func (_c *MockRecordSource_Scan_Call) Return(_a0 error) *MockRecordSource_Scan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRecordSource_Scan_Call) RunAndReturn(run func(context.Context, func(string, sriracha.RawRecord) error) error) *MockRecordSource_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRecordSource creates a new instance of MockRecordSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecordSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecordSource {
	mock := &MockRecordSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
