// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocksriracha

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.sriracha.dev/sriracha"
)

// NewMockRecordSource creates a new instance of MockRecordSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecordSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecordSource {
	mock := &MockRecordSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRecordSource is an autogenerated mock type for the RecordSource type
type MockRecordSource struct {
	mock.Mock
}

type MockRecordSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecordSource) EXPECT() *MockRecordSource_Expecter {
	return &MockRecordSource_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type MockRecordSource
func (_mock *MockRecordSource) Fetch(ctx context.Context, id string) (sriracha.RawRecord, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 sriracha.RawRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (sriracha.RawRecord, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) sriracha.RawRecord); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sriracha.RawRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRecordSource_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockRecordSource_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRecordSource_Expecter) Fetch(ctx interface{}, id interface{}) *MockRecordSource_Fetch_Call {
	return &MockRecordSource_Fetch_Call{Call: _e.mock.On("Fetch", ctx, id)}
}

func (_c *MockRecordSource_Fetch_Call) Run(run func(ctx context.Context, id string)) *MockRecordSource_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRecordSource_Fetch_Call) Return(rawRecord sriracha.RawRecord, err error) *MockRecordSource_Fetch_Call {
	_c.Call.Return(rawRecord, err)
	return _c
}

func (_c *MockRecordSource_Fetch_Call) RunAndReturn(run func(ctx context.Context, id string) (sriracha.RawRecord, error)) *MockRecordSource_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function for the type MockRecordSource
func (_mock *MockRecordSource) Scan(ctx context.Context, fn func(id string, r sriracha.RawRecord) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(id string, r sriracha.RawRecord) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRecordSource_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockRecordSource_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(id string, r sriracha.RawRecord) error
func (_e *MockRecordSource_Expecter) Scan(ctx interface{}, fn interface{}) *MockRecordSource_Scan_Call {
	return &MockRecordSource_Scan_Call{Call: _e.mock.On("Scan", ctx, fn)}
}

func (_c *MockRecordSource_Scan_Call) Run(run func(ctx context.Context, fn func(id string, r sriracha.RawRecord) error)) *MockRecordSource_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(id string, r sriracha.RawRecord) error
		if args[1] != nil {
			arg1 = args[1].(func(id string, r sriracha.RawRecord) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRecordSource_Scan_Call) Return(err error) *MockRecordSource_Scan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRecordSource_Scan_Call) RunAndReturn(run func(ctx context.Context, fn func(id string, r sriracha.RawRecord) error) error) *MockRecordSource_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIncrementalRecordSource creates a new instance of MockIncrementalRecordSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIncrementalRecordSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIncrementalRecordSource {
	mock := &MockIncrementalRecordSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIncrementalRecordSource is an autogenerated mock type for the IncrementalRecordSource type
type MockIncrementalRecordSource struct {
	mock.Mock
}

type MockIncrementalRecordSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIncrementalRecordSource) EXPECT() *MockIncrementalRecordSource_Expecter {
	return &MockIncrementalRecordSource_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type MockIncrementalRecordSource
func (_mock *MockIncrementalRecordSource) Fetch(ctx context.Context, id string) (sriracha.RawRecord, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 sriracha.RawRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (sriracha.RawRecord, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) sriracha.RawRecord); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sriracha.RawRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIncrementalRecordSource_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockIncrementalRecordSource_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIncrementalRecordSource_Expecter) Fetch(ctx interface{}, id interface{}) *MockIncrementalRecordSource_Fetch_Call {
	return &MockIncrementalRecordSource_Fetch_Call{Call: _e.mock.On("Fetch", ctx, id)}
}

func (_c *MockIncrementalRecordSource_Fetch_Call) Run(run func(ctx context.Context, id string)) *MockIncrementalRecordSource_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIncrementalRecordSource_Fetch_Call) Return(rawRecord sriracha.RawRecord, err error) *MockIncrementalRecordSource_Fetch_Call {
	_c.Call.Return(rawRecord, err)
	return _c
}

func (_c *MockIncrementalRecordSource_Fetch_Call) RunAndReturn(run func(ctx context.Context, id string) (sriracha.RawRecord, error)) *MockIncrementalRecordSource_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function for the type MockIncrementalRecordSource
func (_mock *MockIncrementalRecordSource) Scan(ctx context.Context, fn func(id string, r sriracha.RawRecord) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(id string, r sriracha.RawRecord) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncrementalRecordSource_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockIncrementalRecordSource_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(id string, r sriracha.RawRecord) error
func (_e *MockIncrementalRecordSource_Expecter) Scan(ctx interface{}, fn interface{}) *MockIncrementalRecordSource_Scan_Call {
	return &MockIncrementalRecordSource_Scan_Call{Call: _e.mock.On("Scan", ctx, fn)}
}

func (_c *MockIncrementalRecordSource_Scan_Call) Run(run func(ctx context.Context, fn func(id string, r sriracha.RawRecord) error)) *MockIncrementalRecordSource_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(id string, r sriracha.RawRecord) error
		if args[1] != nil {
			arg1 = args[1].(func(id string, r sriracha.RawRecord) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIncrementalRecordSource_Scan_Call) Return(err error) *MockIncrementalRecordSource_Scan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncrementalRecordSource_Scan_Call) RunAndReturn(run func(ctx context.Context, fn func(id string, r sriracha.RawRecord) error) error) *MockIncrementalRecordSource_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// ScanSince provides a mock function for the type MockIncrementalRecordSource
func (_mock *MockIncrementalRecordSource) ScanSince(ctx context.Context, checkpoint string, fn func(id string, r sriracha.RawRecord) error) error {
	ret := _mock.Called(ctx, checkpoint, fn)

	if len(ret) == 0 {
		panic("no return value specified for ScanSince")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, func(id string, r sriracha.RawRecord) error) error); ok {
		r0 = returnFunc(ctx, checkpoint, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncrementalRecordSource_ScanSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScanSince'
type MockIncrementalRecordSource_ScanSince_Call struct {
	*mock.Call
}

// ScanSince is a helper method to define mock.On call
//   - ctx context.Context
//   - checkpoint string
//   - fn func(id string, r sriracha.RawRecord) error
func (_e *MockIncrementalRecordSource_Expecter) ScanSince(ctx interface{}, checkpoint interface{}, fn interface{}) *MockIncrementalRecordSource_ScanSince_Call {
	return &MockIncrementalRecordSource_ScanSince_Call{Call: _e.mock.On("ScanSince", ctx, checkpoint, fn)}
}

func (_c *MockIncrementalRecordSource_ScanSince_Call) Run(run func(ctx context.Context, checkpoint string, fn func(id string, r sriracha.RawRecord) error)) *MockIncrementalRecordSource_ScanSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 func(id string, r sriracha.RawRecord) error
		if args[2] != nil {
			arg2 = args[2].(func(id string, r sriracha.RawRecord) error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIncrementalRecordSource_ScanSince_Call) Return(err error) *MockIncrementalRecordSource_ScanSince_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncrementalRecordSource_ScanSince_Call) RunAndReturn(run func(ctx context.Context, checkpoint string, fn func(id string, r sriracha.RawRecord) error) error) *MockIncrementalRecordSource_ScanSince_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenIndexer creates a new instance of MockTokenIndexer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenIndexer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenIndexer {
	mock := &MockTokenIndexer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenIndexer is an autogenerated mock type for the TokenIndexer type
type MockTokenIndexer struct {
	mock.Mock
}

type MockTokenIndexer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenIndexer) EXPECT() *MockTokenIndexer_Expecter {
	return &MockTokenIndexer_Expecter{mock: &_m.Mock}
}

// Match provides a mock function for the type MockTokenIndexer
func (_mock *MockTokenIndexer) Match(ctx context.Context, tr sriracha.TokenRecord, cfg sriracha.MatchConfig) ([]sriracha.Candidate, error) {
	ret := _mock.Called(ctx, tr, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Match")
	}

	var r0 []sriracha.Candidate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sriracha.TokenRecord, sriracha.MatchConfig) ([]sriracha.Candidate, error)); ok {
		return returnFunc(ctx, tr, cfg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sriracha.TokenRecord, sriracha.MatchConfig) []sriracha.Candidate); ok {
		r0 = returnFunc(ctx, tr, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sriracha.Candidate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sriracha.TokenRecord, sriracha.MatchConfig) error); ok {
		r1 = returnFunc(ctx, tr, cfg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenIndexer_Match_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Match'
type MockTokenIndexer_Match_Call struct {
	*mock.Call
}

// Match is a helper method to define mock.On call
//   - ctx context.Context
//   - tr sriracha.TokenRecord
//   - cfg sriracha.MatchConfig
func (_e *MockTokenIndexer_Expecter) Match(ctx interface{}, tr interface{}, cfg interface{}) *MockTokenIndexer_Match_Call {
	return &MockTokenIndexer_Match_Call{Call: _e.mock.On("Match", ctx, tr, cfg)}
}

func (_c *MockTokenIndexer_Match_Call) Run(run func(ctx context.Context, tr sriracha.TokenRecord, cfg sriracha.MatchConfig)) *MockTokenIndexer_Match_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sriracha.TokenRecord
		if args[1] != nil {
			arg1 = args[1].(sriracha.TokenRecord)
		}
		var arg2 sriracha.MatchConfig
		if args[2] != nil {
			arg2 = args[2].(sriracha.MatchConfig)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenIndexer_Match_Call) Return(candidates []sriracha.Candidate, err error) *MockTokenIndexer_Match_Call {
	_c.Call.Return(candidates, err)
	return _c
}

func (_c *MockTokenIndexer_Match_Call) RunAndReturn(run func(ctx context.Context, tr sriracha.TokenRecord, cfg sriracha.MatchConfig) ([]sriracha.Candidate, error)) *MockTokenIndexer_Match_Call {
	_c.Call.Return(run)
	return _c
}

// Rebuild provides a mock function for the type MockTokenIndexer
func (_mock *MockTokenIndexer) Rebuild(ctx context.Context, src sriracha.RecordSource) error {
	ret := _mock.Called(ctx, src)

	if len(ret) == 0 {
		panic("no return value specified for Rebuild")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sriracha.RecordSource) error); ok {
		r0 = returnFunc(ctx, src)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenIndexer_Rebuild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rebuild'
type MockTokenIndexer_Rebuild_Call struct {
	*mock.Call
}

// Rebuild is a helper method to define mock.On call
//   - ctx context.Context
//   - src sriracha.RecordSource
func (_e *MockTokenIndexer_Expecter) Rebuild(ctx interface{}, src interface{}) *MockTokenIndexer_Rebuild_Call {
	return &MockTokenIndexer_Rebuild_Call{Call: _e.mock.On("Rebuild", ctx, src)}
}

func (_c *MockTokenIndexer_Rebuild_Call) Run(run func(ctx context.Context, src sriracha.RecordSource)) *MockTokenIndexer_Rebuild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sriracha.RecordSource
		if args[1] != nil {
			arg1 = args[1].(sriracha.RecordSource)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenIndexer_Rebuild_Call) Return(err error) *MockTokenIndexer_Rebuild_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenIndexer_Rebuild_Call) RunAndReturn(run func(ctx context.Context, src sriracha.RecordSource) error) *MockTokenIndexer_Rebuild_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function for the type MockTokenIndexer
func (_mock *MockTokenIndexer) Stats() sriracha.IndexStats {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 sriracha.IndexStats
	if returnFunc, ok := ret.Get(0).(func() sriracha.IndexStats); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(sriracha.IndexStats)
	}
	return r0
}

// MockTokenIndexer_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockTokenIndexer_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockTokenIndexer_Expecter) Stats() *MockTokenIndexer_Stats_Call {
	return &MockTokenIndexer_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockTokenIndexer_Stats_Call) Run(run func()) *MockTokenIndexer_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenIndexer_Stats_Call) Return(indexStats sriracha.IndexStats) *MockTokenIndexer_Stats_Call {
	_c.Call.Return(indexStats)
	return _c
}

func (_c *MockTokenIndexer_Stats_Call) RunAndReturn(run func() sriracha.IndexStats) *MockTokenIndexer_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function for the type MockTokenIndexer
func (_mock *MockTokenIndexer) Sync(ctx context.Context, src sriracha.IncrementalRecordSource) error {
	ret := _mock.Called(ctx, src)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sriracha.IncrementalRecordSource) error); ok {
		r0 = returnFunc(ctx, src)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenIndexer_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockTokenIndexer_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - ctx context.Context
//   - src sriracha.IncrementalRecordSource
func (_e *MockTokenIndexer_Expecter) Sync(ctx interface{}, src interface{}) *MockTokenIndexer_Sync_Call {
	return &MockTokenIndexer_Sync_Call{Call: _e.mock.On("Sync", ctx, src)}
}

func (_c *MockTokenIndexer_Sync_Call) Run(run func(ctx context.Context, src sriracha.IncrementalRecordSource)) *MockTokenIndexer_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sriracha.IncrementalRecordSource
		if args[1] != nil {
			arg1 = args[1].(sriracha.IncrementalRecordSource)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenIndexer_Sync_Call) Return(err error) *MockTokenIndexer_Sync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenIndexer_Sync_Call) RunAndReturn(run func(ctx context.Context, src sriracha.IncrementalRecordSource) error) *MockTokenIndexer_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIndexStorage creates a new instance of MockIndexStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIndexStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIndexStorage {
	mock := &MockIndexStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIndexStorage is an autogenerated mock type for the IndexStorage type
type MockIndexStorage struct {
	mock.Mock
}

type MockIndexStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIndexStorage) EXPECT() *MockIndexStorage_Expecter {
	return &MockIndexStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockIndexStorage
func (_mock *MockIndexStorage) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIndexStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIndexStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockIndexStorage_Expecter) Delete(ctx interface{}, key interface{}) *MockIndexStorage_Delete_Call {
	return &MockIndexStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockIndexStorage_Delete_Call) Run(run func(ctx context.Context, key string)) *MockIndexStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIndexStorage_Delete_Call) Return(err error) *MockIndexStorage_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIndexStorage_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockIndexStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockIndexStorage
func (_mock *MockIndexStorage) Get(ctx context.Context, key string) ([]byte, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIndexStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIndexStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockIndexStorage_Expecter) Get(ctx interface{}, key interface{}) *MockIndexStorage_Get_Call {
	return &MockIndexStorage_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockIndexStorage_Get_Call) Run(run func(ctx context.Context, key string)) *MockIndexStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIndexStorage_Get_Call) Return(bytes []byte, err error) *MockIndexStorage_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockIndexStorage_Get_Call) RunAndReturn(run func(ctx context.Context, key string) ([]byte, error)) *MockIndexStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// LoadCheckpoint provides a mock function for the type MockIndexStorage
func (_mock *MockIndexStorage) LoadCheckpoint(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadCheckpoint")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIndexStorage_LoadCheckpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadCheckpoint'
type MockIndexStorage_LoadCheckpoint_Call struct {
	*mock.Call
}

// LoadCheckpoint is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIndexStorage_Expecter) LoadCheckpoint(ctx interface{}) *MockIndexStorage_LoadCheckpoint_Call {
	return &MockIndexStorage_LoadCheckpoint_Call{Call: _e.mock.On("LoadCheckpoint", ctx)}
}

func (_c *MockIndexStorage_LoadCheckpoint_Call) Run(run func(ctx context.Context)) *MockIndexStorage_LoadCheckpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIndexStorage_LoadCheckpoint_Call) Return(s string, err error) *MockIndexStorage_LoadCheckpoint_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIndexStorage_LoadCheckpoint_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockIndexStorage_LoadCheckpoint_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockIndexStorage
func (_mock *MockIndexStorage) Put(ctx context.Context, key string, value []byte) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIndexStorage_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockIndexStorage_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value []byte
func (_e *MockIndexStorage_Expecter) Put(ctx interface{}, key interface{}, value interface{}) *MockIndexStorage_Put_Call {
	return &MockIndexStorage_Put_Call{Call: _e.mock.On("Put", ctx, key, value)}
}

func (_c *MockIndexStorage_Put_Call) Run(run func(ctx context.Context, key string, value []byte)) *MockIndexStorage_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIndexStorage_Put_Call) Return(err error) *MockIndexStorage_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIndexStorage_Put_Call) RunAndReturn(run func(ctx context.Context, key string, value []byte) error) *MockIndexStorage_Put_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCheckpoint provides a mock function for the type MockIndexStorage
func (_mock *MockIndexStorage) SaveCheckpoint(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for SaveCheckpoint")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIndexStorage_SaveCheckpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCheckpoint'
type MockIndexStorage_SaveCheckpoint_Call struct {
	*mock.Call
}

// SaveCheckpoint is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockIndexStorage_Expecter) SaveCheckpoint(ctx interface{}, token interface{}) *MockIndexStorage_SaveCheckpoint_Call {
	return &MockIndexStorage_SaveCheckpoint_Call{Call: _e.mock.On("SaveCheckpoint", ctx, token)}
}

func (_c *MockIndexStorage_SaveCheckpoint_Call) Run(run func(ctx context.Context, token string)) *MockIndexStorage_SaveCheckpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIndexStorage_SaveCheckpoint_Call) Return(err error) *MockIndexStorage_SaveCheckpoint_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIndexStorage_SaveCheckpoint_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockIndexStorage_SaveCheckpoint_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function for the type MockIndexStorage
func (_mock *MockIndexStorage) Scan(ctx context.Context, prefix string, fn func(key string, value []byte) error) error {
	ret := _mock.Called(ctx, prefix, fn)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, func(key string, value []byte) error) error); ok {
		r0 = returnFunc(ctx, prefix, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIndexStorage_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockIndexStorage_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
//   - fn func(key string, value []byte) error
func (_e *MockIndexStorage_Expecter) Scan(ctx interface{}, prefix interface{}, fn interface{}) *MockIndexStorage_Scan_Call {
	return &MockIndexStorage_Scan_Call{Call: _e.mock.On("Scan", ctx, prefix, fn)}
}

func (_c *MockIndexStorage_Scan_Call) Run(run func(ctx context.Context, prefix string, fn func(key string, value []byte) error)) *MockIndexStorage_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 func(key string, value []byte) error
		if args[2] != nil {
			arg2 = args[2].(func(key string, value []byte) error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIndexStorage_Scan_Call) Return(err error) *MockIndexStorage_Scan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIndexStorage_Scan_Call) RunAndReturn(run func(ctx context.Context, prefix string, fn func(key string, value []byte) error) error) *MockIndexStorage_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditLog creates a new instance of MockAuditLog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditLog(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditLog {
	mock := &MockAuditLog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditLog is an autogenerated mock type for the AuditLog type
type MockAuditLog struct {
	mock.Mock
}

type MockAuditLog_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditLog) EXPECT() *MockAuditLog_Expecter {
	return &MockAuditLog_Expecter{mock: &_m.Mock}
}

// Append provides a mock function for the type MockAuditLog
func (_mock *MockAuditLog) Append(ctx context.Context, event sriracha.AuditEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sriracha.AuditEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditLog_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockAuditLog_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - event sriracha.AuditEvent
func (_e *MockAuditLog_Expecter) Append(ctx interface{}, event interface{}) *MockAuditLog_Append_Call {
	return &MockAuditLog_Append_Call{Call: _e.mock.On("Append", ctx, event)}
}

func (_c *MockAuditLog_Append_Call) Run(run func(ctx context.Context, event sriracha.AuditEvent)) *MockAuditLog_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sriracha.AuditEvent
		if args[1] != nil {
			arg1 = args[1].(sriracha.AuditEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditLog_Append_Call) Return(err error) *MockAuditLog_Append_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditLog_Append_Call) RunAndReturn(run func(ctx context.Context, event sriracha.AuditEvent) error) *MockAuditLog_Append_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockAuditLog
func (_mock *MockAuditLog) Verify(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditLog_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockAuditLog_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuditLog_Expecter) Verify(ctx interface{}) *MockAuditLog_Verify_Call {
	return &MockAuditLog_Verify_Call{Call: _e.mock.On("Verify", ctx)}
}

func (_c *MockAuditLog_Verify_Call) Run(run func(ctx context.Context)) *MockAuditLog_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuditLog_Verify_Call) Return(err error) *MockAuditLog_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditLog_Verify_Call) RunAndReturn(run func(ctx context.Context) error) *MockAuditLog_Verify_Call {
	_c.Call.Return(run)
	return _c
}
