version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - copyloopvar
    - errorlint
    - forcetypeassert
    - gosec
  settings:
    gosec:
      excludes:
        - G304

formatters:
  enable:
    - gofmt
    - goimports
