force-file-write: true
formatter: goimports
log-level: info

structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: 'mock{{.SrcPackageName}}'

template: testify
template-schema: '{{.Template}}.schema.json'

packages:
  github.com/ccuetoh/sriracha:
    config:
      all: true
      recursive: true
      dir: 'mock/{{.SrcPackageName}}'
      filename: "mocks.go"