log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
outpkg: 'mock{{.PackageName}}'
packages:
  go.sriracha.dev:
    config:
      all: true
      recursive: true
      dir: 'mock/{{.PackageName}}'
      filename: "mock_{{.InterfaceName}}.go"
