// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockserver

import (
	"context"
	"net"

	mock "github.com/stretchr/testify/mock"
)

// NewMockServer creates a new instance of MockServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServer {
	mock := &MockServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServer is an autogenerated mock type for the Server type
type MockServer struct {
	mock.Mock
}

type MockServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServer) EXPECT() *MockServer_Expecter {
	return &MockServer_Expecter{mock: &_m.Mock}
}

// GracefulStop provides a mock function for the type MockServer
func (_mock *MockServer) GracefulStop(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockServer_GracefulStop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GracefulStop'
type MockServer_GracefulStop_Call struct {
	*mock.Call
}

// GracefulStop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServer_Expecter) GracefulStop(ctx interface{}) *MockServer_GracefulStop_Call {
	return &MockServer_GracefulStop_Call{Call: _e.mock.On("GracefulStop", ctx)}
}

func (_c *MockServer_GracefulStop_Call) Run(run func(ctx context.Context)) *MockServer_GracefulStop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServer_GracefulStop_Call) Return() *MockServer_GracefulStop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServer_GracefulStop_Call) RunAndReturn(run func(ctx context.Context)) *MockServer_GracefulStop_Call {
	_c.Run(run)
	return _c
}

// Serve provides a mock function for the type MockServer
func (_mock *MockServer) Serve(lis net.Listener) error {
	ret := _mock.Called(lis)

	if len(ret) == 0 {
		panic("no return value specified for Serve")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(net.Listener) error); ok {
		r0 = returnFunc(lis)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServer_Serve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serve'
type MockServer_Serve_Call struct {
	*mock.Call
}

// Serve is a helper method to define mock.On call
//   - lis net.Listener
func (_e *MockServer_Expecter) Serve(lis interface{}) *MockServer_Serve_Call {
	return &MockServer_Serve_Call{Call: _e.mock.On("Serve", lis)}
}

func (_c *MockServer_Serve_Call) Run(run func(lis net.Listener)) *MockServer_Serve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 net.Listener
		if args[0] != nil {
			arg0 = args[0].(net.Listener)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServer_Serve_Call) Return(err error) *MockServer_Serve_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServer_Serve_Call) RunAndReturn(run func(lis net.Listener) error) *MockServer_Serve_Call {
	_c.Call.Return(run)
	return _c
}
