// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockindexer

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStorageSizer is an autogenerated mock type for the StorageSizer type
type MockStorageSizer struct {
	mock.Mock
}

type MockStorageSizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageSizer) EXPECT() *MockStorageSizer_Expecter {
	return &MockStorageSizer_Expecter{mock: &_m.Mock}
}

// SizeBytes provides a mock function with given fields: ctx
func (_m *MockStorageSizer) SizeBytes(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SizeBytes")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorageSizer_SizeBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SizeBytes'
type MockStorageSizer_SizeBytes_Call struct {
	*mock.Call
}

// SizeBytes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorageSizer_Expecter) SizeBytes(ctx interface{}) *MockStorageSizer_SizeBytes_Call {
	return &MockStorageSizer_SizeBytes_Call{Call: _e.mock.On("SizeBytes", ctx)}
}

func (_c *MockStorageSizer_SizeBytes_Call) Run(run func(ctx context.Context)) *MockStorageSizer_SizeBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStorageSizer_SizeBytes_Call) Return(_a0 int64, _a1 error) *MockStorageSizer_SizeBytes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorageSizer_SizeBytes_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockStorageSizer_SizeBytes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorageSizer creates a new instance of MockStorageSizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageSizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageSizer {
	mock := &MockStorageSizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
