// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockindexer

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStorageSizer creates a new instance of MockStorageSizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageSizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageSizer {
	mock := &MockStorageSizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorageSizer is an autogenerated mock type for the StorageSizer type
type MockStorageSizer struct {
	mock.Mock
}

type MockStorageSizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageSizer) EXPECT() *MockStorageSizer_Expecter {
	return &MockStorageSizer_Expecter{mock: &_m.Mock}
}

// SizeBytes provides a mock function for the type MockStorageSizer
func (_mock *MockStorageSizer) SizeBytes(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SizeBytes")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageSizer_SizeBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SizeBytes'
type MockStorageSizer_SizeBytes_Call struct {
	*mock.Call
}

// SizeBytes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorageSizer_Expecter) SizeBytes(ctx interface{}) *MockStorageSizer_SizeBytes_Call {
	return &MockStorageSizer_SizeBytes_Call{Call: _e.mock.On("SizeBytes", ctx)}
}

func (_c *MockStorageSizer_SizeBytes_Call) Run(run func(ctx context.Context)) *MockStorageSizer_SizeBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorageSizer_SizeBytes_Call) Return(n int64, err error) *MockStorageSizer_SizeBytes_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStorageSizer_SizeBytes_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockStorageSizer_SizeBytes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactor creates a new instance of MockTransactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactor {
	mock := &MockTransactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactor is an autogenerated mock type for the Transactor type
type MockTransactor struct {
	mock.Mock
}

type MockTransactor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactor) EXPECT() *MockTransactor_Expecter {
	return &MockTransactor_Expecter{mock: &_m.Mock}
}

// DeleteBatch provides a mock function for the type MockTransactor
func (_mock *MockTransactor) DeleteBatch(ctx context.Context, keys []string) error {
	ret := _mock.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, keys)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactor_DeleteBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBatch'
type MockTransactor_DeleteBatch_Call struct {
	*mock.Call
}

// DeleteBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
func (_e *MockTransactor_Expecter) DeleteBatch(ctx interface{}, keys interface{}) *MockTransactor_DeleteBatch_Call {
	return &MockTransactor_DeleteBatch_Call{Call: _e.mock.On("DeleteBatch", ctx, keys)}
}

func (_c *MockTransactor_DeleteBatch_Call) Run(run func(ctx context.Context, keys []string)) *MockTransactor_DeleteBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactor_DeleteBatch_Call) Return(err error) *MockTransactor_DeleteBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactor_DeleteBatch_Call) RunAndReturn(run func(ctx context.Context, keys []string) error) *MockTransactor_DeleteBatch_Call {
	_c.Call.Return(run)
	return _c
}

// PutBatch provides a mock function for the type MockTransactor
func (_mock *MockTransactor) PutBatch(ctx context.Context, kvs map[string][]byte) error {
	ret := _mock.Called(ctx, kvs)

	if len(ret) == 0 {
		panic("no return value specified for PutBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string][]byte) error); ok {
		r0 = returnFunc(ctx, kvs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactor_PutBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutBatch'
type MockTransactor_PutBatch_Call struct {
	*mock.Call
}

// PutBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - kvs map[string][]byte
func (_e *MockTransactor_Expecter) PutBatch(ctx interface{}, kvs interface{}) *MockTransactor_PutBatch_Call {
	return &MockTransactor_PutBatch_Call{Call: _e.mock.On("PutBatch", ctx, kvs)}
}

func (_c *MockTransactor_PutBatch_Call) Run(run func(ctx context.Context, kvs map[string][]byte)) *MockTransactor_PutBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string][]byte
		if args[1] != nil {
			arg1 = args[1].(map[string][]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactor_PutBatch_Call) Return(err error) *MockTransactor_PutBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactor_PutBatch_Call) RunAndReturn(run func(ctx context.Context, kvs map[string][]byte) error) *MockTransactor_PutBatch_Call {
	_c.Call.Return(run)
	return _c
}
