// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockindexer

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTransactor is an autogenerated mock type for the Transactor type
type MockTransactor struct {
	mock.Mock
}

type MockTransactor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactor) EXPECT() *MockTransactor_Expecter {
	return &MockTransactor_Expecter{mock: &_m.Mock}
}

// DeleteBatch provides a mock function with given fields: ctx, keys
func (_m *MockTransactor) DeleteBatch(ctx context.Context, keys []string) error {
	ret := _m.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, keys)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactor_DeleteBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBatch'
type MockTransactor_DeleteBatch_Call struct {
	*mock.Call
}

// DeleteBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
func (_e *MockTransactor_Expecter) DeleteBatch(ctx interface{}, keys interface{}) *MockTransactor_DeleteBatch_Call {
	return &MockTransactor_DeleteBatch_Call{Call: _e.mock.On("DeleteBatch", ctx, keys)}
}

func (_c *MockTransactor_DeleteBatch_Call) Run(run func(ctx context.Context, keys []string)) *MockTransactor_DeleteBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockTransactor_DeleteBatch_Call) Return(_a0 error) *MockTransactor_DeleteBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactor_DeleteBatch_Call) RunAndReturn(run func(context.Context, []string) error) *MockTransactor_DeleteBatch_Call {
	_c.Call.Return(run)
	return _c
}

// PutBatch provides a mock function with given fields: ctx, kvs
func (_m *MockTransactor) PutBatch(ctx context.Context, kvs map[string][]byte) error {
	ret := _m.Called(ctx, kvs)

	if len(ret) == 0 {
		panic("no return value specified for PutBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string][]byte) error); ok {
		r0 = rf(ctx, kvs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactor_PutBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutBatch'
type MockTransactor_PutBatch_Call struct {
	*mock.Call
}

// PutBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - kvs map[string][]byte
func (_e *MockTransactor_Expecter) PutBatch(ctx interface{}, kvs interface{}) *MockTransactor_PutBatch_Call {
	return &MockTransactor_PutBatch_Call{Call: _e.mock.On("PutBatch", ctx, kvs)}
}

func (_c *MockTransactor_PutBatch_Call) Run(run func(ctx context.Context, kvs map[string][]byte)) *MockTransactor_PutBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string][]byte))
	})
	return _c
}

func (_c *MockTransactor_PutBatch_Call) Return(_a0 error) *MockTransactor_PutBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactor_PutBatch_Call) RunAndReturn(run func(context.Context, map[string][]byte) error) *MockTransactor_PutBatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactor creates a new instance of MockTransactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactor {
	mock := &MockTransactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
