// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockclient

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	srirachav1 "go.sriracha.dev/transport/proto/srirachav1"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// BulkLink provides a mock function with given fields: ctx
func (_m *MockClient) BulkLink(ctx context.Context) (grpc.BidiStreamingClient[srirachav1.BulkTokenBatch, srirachav1.BulkMatchResult], error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BulkLink")
	}

	var r0 grpc.BidiStreamingClient[srirachav1.BulkTokenBatch, srirachav1.BulkMatchResult]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (grpc.BidiStreamingClient[srirachav1.BulkTokenBatch, srirachav1.BulkMatchResult], error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) grpc.BidiStreamingClient[srirachav1.BulkTokenBatch, srirachav1.BulkMatchResult]); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.BidiStreamingClient[srirachav1.BulkTokenBatch, srirachav1.BulkMatchResult])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_BulkLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkLink'
type MockClient_BulkLink_Call struct {
	*mock.Call
}

// BulkLink is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) BulkLink(ctx interface{}) *MockClient_BulkLink_Call {
	return &MockClient_BulkLink_Call{Call: _e.mock.On("BulkLink", ctx)}
}

func (_c *MockClient_BulkLink_Call) Run(run func(ctx context.Context)) *MockClient_BulkLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_BulkLink_Call) Return(_a0 grpc.BidiStreamingClient[srirachav1.BulkTokenBatch, srirachav1.BulkMatchResult], _a1 error) *MockClient_BulkLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_BulkLink_Call) RunAndReturn(run func(context.Context) (grpc.BidiStreamingClient[srirachav1.BulkTokenBatch, srirachav1.BulkMatchResult], error)) *MockClient_BulkLink_Call {
	_c.Call.Return(run)
	return _c
}

// Capabilities provides a mock function with no fields
func (_m *MockClient) Capabilities() *srirachav1.CapabilitiesResponse {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Capabilities")
	}

	var r0 *srirachav1.CapabilitiesResponse
	if rf, ok := ret.Get(0).(func() *srirachav1.CapabilitiesResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*srirachav1.CapabilitiesResponse)
		}
	}

	return r0
}

// MockClient_Capabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Capabilities'
type MockClient_Capabilities_Call struct {
	*mock.Call
}

// Capabilities is a helper method to define mock.On call
func (_e *MockClient_Expecter) Capabilities() *MockClient_Capabilities_Call {
	return &MockClient_Capabilities_Call{Call: _e.mock.On("Capabilities")}
}

func (_c *MockClient_Capabilities_Call) Run(run func()) *MockClient_Capabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Capabilities_Call) Return(_a0 *srirachav1.CapabilitiesResponse) *MockClient_Capabilities_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Capabilities_Call) RunAndReturn(run func() *srirachav1.CapabilitiesResponse) *MockClient_Capabilities_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(_a0 error) *MockClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: ctx, req
func (_m *MockClient) Query(ctx context.Context, req *srirachav1.QueryRequest) (*srirachav1.QueryResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *srirachav1.QueryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *srirachav1.QueryRequest) (*srirachav1.QueryResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *srirachav1.QueryRequest) *srirachav1.QueryResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*srirachav1.QueryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *srirachav1.QueryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockClient_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - req *srirachav1.QueryRequest
func (_e *MockClient_Expecter) Query(ctx interface{}, req interface{}) *MockClient_Query_Call {
	return &MockClient_Query_Call{Call: _e.mock.On("Query", ctx, req)}
}

func (_c *MockClient_Query_Call) Run(run func(ctx context.Context, req *srirachav1.QueryRequest)) *MockClient_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*srirachav1.QueryRequest))
	})
	return _c
}

func (_c *MockClient_Query_Call) Return(_a0 *srirachav1.QueryResponse, _a1 error) *MockClient_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Query_Call) RunAndReturn(run func(context.Context, *srirachav1.QueryRequest) (*srirachav1.QueryResponse, error)) *MockClient_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
