// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockclient

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.sriracha.dev/transport/proto/sriracha/v1"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// BulkLink provides a mock function for the type MockClient
func (_mock *MockClient) BulkLink(ctx context.Context) (srirachav1.SrirachaService_BulkLinkClient, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BulkLink")
	}

	var r0 srirachav1.SrirachaService_BulkLinkClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (srirachav1.SrirachaService_BulkLinkClient, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) srirachav1.SrirachaService_BulkLinkClient); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(srirachav1.SrirachaService_BulkLinkClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_BulkLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkLink'
type MockClient_BulkLink_Call struct {
	*mock.Call
}

// BulkLink is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) BulkLink(ctx interface{}) *MockClient_BulkLink_Call {
	return &MockClient_BulkLink_Call{Call: _e.mock.On("BulkLink", ctx)}
}

func (_c *MockClient_BulkLink_Call) Run(run func(ctx context.Context)) *MockClient_BulkLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_BulkLink_Call) Return(v srirachav1.SrirachaService_BulkLinkClient, err error) *MockClient_BulkLink_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_BulkLink_Call) RunAndReturn(run func(ctx context.Context) (srirachav1.SrirachaService_BulkLinkClient, error)) *MockClient_BulkLink_Call {
	_c.Call.Return(run)
	return _c
}

// Capabilities provides a mock function for the type MockClient
func (_mock *MockClient) Capabilities() *srirachav1.GetCapabilitiesResponse {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Capabilities")
	}

	var r0 *srirachav1.GetCapabilitiesResponse
	if returnFunc, ok := ret.Get(0).(func() *srirachav1.GetCapabilitiesResponse); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*srirachav1.GetCapabilitiesResponse)
		}
	}
	return r0
}

// MockClient_Capabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Capabilities'
type MockClient_Capabilities_Call struct {
	*mock.Call
}

// Capabilities is a helper method to define mock.On call
func (_e *MockClient_Expecter) Capabilities() *MockClient_Capabilities_Call {
	return &MockClient_Capabilities_Call{Call: _e.mock.On("Capabilities")}
}

func (_c *MockClient_Capabilities_Call) Run(run func()) *MockClient_Capabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Capabilities_Call) Return(getCapabilitiesResponse *srirachav1.GetCapabilitiesResponse) *MockClient_Capabilities_Call {
	_c.Call.Return(getCapabilitiesResponse)
	return _c
}

func (_c *MockClient_Capabilities_Call) RunAndReturn(run func() *srirachav1.GetCapabilitiesResponse) *MockClient_Capabilities_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockClient
func (_mock *MockClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(err error) *MockClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockClient
func (_mock *MockClient) Query(ctx context.Context, req *srirachav1.QueryRequest) (*srirachav1.QueryResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *srirachav1.QueryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *srirachav1.QueryRequest) (*srirachav1.QueryResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *srirachav1.QueryRequest) *srirachav1.QueryResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*srirachav1.QueryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *srirachav1.QueryRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockClient_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - req *srirachav1.QueryRequest
func (_e *MockClient_Expecter) Query(ctx interface{}, req interface{}) *MockClient_Query_Call {
	return &MockClient_Query_Call{Call: _e.mock.On("Query", ctx, req)}
}

func (_c *MockClient_Query_Call) Run(run func(ctx context.Context, req *srirachav1.QueryRequest)) *MockClient_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *srirachav1.QueryRequest
		if args[1] != nil {
			arg1 = args[1].(*srirachav1.QueryRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_Query_Call) Return(queryResponse *srirachav1.QueryResponse, err error) *MockClient_Query_Call {
	_c.Call.Return(queryResponse, err)
	return _c
}

func (_c *MockClient_Query_Call) RunAndReturn(run func(ctx context.Context, req *srirachav1.QueryRequest) (*srirachav1.QueryResponse, error)) *MockClient_Query_Call {
	_c.Call.Return(run)
	return _c
}
