// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocksession

import (
	"github.com/ccuetoh/sriracha"
	"github.com/ccuetoh/sriracha/token"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSession creates a new instance of MockSession. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSession {
	mock := &MockSession{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSession is an autogenerated mock type for the Session type
type MockSession struct {
	mock.Mock
}

type MockSession_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSession) EXPECT() *MockSession_Expecter {
	return &MockSession_Expecter{mock: &_m.Mock}
}

// Destroy provides a mock function for the type MockSession
func (_mock *MockSession) Destroy() {
	_mock.Called()
	return
}

// MockSession_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockSession_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
func (_e *MockSession_Expecter) Destroy() *MockSession_Destroy_Call {
	return &MockSession_Destroy_Call{Call: _e.mock.On("Destroy")}
}

func (_c *MockSession_Destroy_Call) Run(run func()) *MockSession_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSession_Destroy_Call) Return() *MockSession_Destroy_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSession_Destroy_Call) RunAndReturn(run func()) *MockSession_Destroy_Call {
	_c.Run(run)
	return _c
}

// Equal provides a mock function for the type MockSession
func (_mock *MockSession) Equal(a sriracha.DeterministicToken, b sriracha.DeterministicToken) bool {
	ret := _mock.Called(a, b)

	if len(ret) == 0 {
		panic("no return value specified for Equal")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(sriracha.DeterministicToken, sriracha.DeterministicToken) bool); ok {
		r0 = returnFunc(a, b)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSession_Equal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Equal'
type MockSession_Equal_Call struct {
	*mock.Call
}

// Equal is a helper method to define mock.On call
//   - a sriracha.DeterministicToken
//   - b sriracha.DeterministicToken
func (_e *MockSession_Expecter) Equal(a interface{}, b interface{}) *MockSession_Equal_Call {
	return &MockSession_Equal_Call{Call: _e.mock.On("Equal", a, b)}
}

func (_c *MockSession_Equal_Call) Run(run func(a sriracha.DeterministicToken, b sriracha.DeterministicToken)) *MockSession_Equal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sriracha.DeterministicToken
		if args[0] != nil {
			arg0 = args[0].(sriracha.DeterministicToken)
		}
		var arg1 sriracha.DeterministicToken
		if args[1] != nil {
			arg1 = args[1].(sriracha.DeterministicToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSession_Equal_Call) Return(b1 bool) *MockSession_Equal_Call {
	_c.Call.Return(b1)
	return _c
}

func (_c *MockSession_Equal_Call) RunAndReturn(run func(a sriracha.DeterministicToken, b sriracha.DeterministicToken) bool) *MockSession_Equal_Call {
	_c.Call.Return(run)
	return _c
}

// FieldSet provides a mock function for the type MockSession
func (_mock *MockSession) FieldSet() sriracha.FieldSet {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FieldSet")
	}

	var r0 sriracha.FieldSet
	if returnFunc, ok := ret.Get(0).(func() sriracha.FieldSet); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(sriracha.FieldSet)
	}
	return r0
}

// MockSession_FieldSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FieldSet'
type MockSession_FieldSet_Call struct {
	*mock.Call
}

// FieldSet is a helper method to define mock.On call
func (_e *MockSession_Expecter) FieldSet() *MockSession_FieldSet_Call {
	return &MockSession_FieldSet_Call{Call: _e.mock.On("FieldSet")}
}

func (_c *MockSession_FieldSet_Call) Run(run func()) *MockSession_FieldSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSession_FieldSet_Call) Return(fieldSet sriracha.FieldSet) *MockSession_FieldSet_Call {
	_c.Call.Return(fieldSet)
	return _c
}

func (_c *MockSession_FieldSet_Call) RunAndReturn(run func() sriracha.FieldSet) *MockSession_FieldSet_Call {
	_c.Call.Return(run)
	return _c
}

// Match provides a mock function for the type MockSession
func (_mock *MockSession) Match(a sriracha.BloomToken, b sriracha.BloomToken, threshold float64) (token.MatchResult, error) {
	ret := _mock.Called(a, b, threshold)

	if len(ret) == 0 {
		panic("no return value specified for Match")
	}

	var r0 token.MatchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(sriracha.BloomToken, sriracha.BloomToken, float64) (token.MatchResult, error)); ok {
		return returnFunc(a, b, threshold)
	}
	if returnFunc, ok := ret.Get(0).(func(sriracha.BloomToken, sriracha.BloomToken, float64) token.MatchResult); ok {
		r0 = returnFunc(a, b, threshold)
	} else {
		r0 = ret.Get(0).(token.MatchResult)
	}
	if returnFunc, ok := ret.Get(1).(func(sriracha.BloomToken, sriracha.BloomToken, float64) error); ok {
		r1 = returnFunc(a, b, threshold)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSession_Match_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Match'
type MockSession_Match_Call struct {
	*mock.Call
}

// Match is a helper method to define mock.On call
//   - a sriracha.BloomToken
//   - b sriracha.BloomToken
//   - threshold float64
func (_e *MockSession_Expecter) Match(a interface{}, b interface{}, threshold interface{}) *MockSession_Match_Call {
	return &MockSession_Match_Call{Call: _e.mock.On("Match", a, b, threshold)}
}

func (_c *MockSession_Match_Call) Run(run func(a sriracha.BloomToken, b sriracha.BloomToken, threshold float64)) *MockSession_Match_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sriracha.BloomToken
		if args[0] != nil {
			arg0 = args[0].(sriracha.BloomToken)
		}
		var arg1 sriracha.BloomToken
		if args[1] != nil {
			arg1 = args[1].(sriracha.BloomToken)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSession_Match_Call) Return(matchResult token.MatchResult, err error) *MockSession_Match_Call {
	_c.Call.Return(matchResult, err)
	return _c
}

func (_c *MockSession_Match_Call) RunAndReturn(run func(a sriracha.BloomToken, b sriracha.BloomToken, threshold float64) (token.MatchResult, error)) *MockSession_Match_Call {
	_c.Call.Return(run)
	return _c
}

// Tokenize provides a mock function for the type MockSession
func (_mock *MockSession) Tokenize(record sriracha.RawRecord) (sriracha.DeterministicToken, error) {
	ret := _mock.Called(record)

	if len(ret) == 0 {
		panic("no return value specified for Tokenize")
	}

	var r0 sriracha.DeterministicToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(sriracha.RawRecord) (sriracha.DeterministicToken, error)); ok {
		return returnFunc(record)
	}
	if returnFunc, ok := ret.Get(0).(func(sriracha.RawRecord) sriracha.DeterministicToken); ok {
		r0 = returnFunc(record)
	} else {
		r0 = ret.Get(0).(sriracha.DeterministicToken)
	}
	if returnFunc, ok := ret.Get(1).(func(sriracha.RawRecord) error); ok {
		r1 = returnFunc(record)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSession_Tokenize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tokenize'
type MockSession_Tokenize_Call struct {
	*mock.Call
}

// Tokenize is a helper method to define mock.On call
//   - record sriracha.RawRecord
func (_e *MockSession_Expecter) Tokenize(record interface{}) *MockSession_Tokenize_Call {
	return &MockSession_Tokenize_Call{Call: _e.mock.On("Tokenize", record)}
}

func (_c *MockSession_Tokenize_Call) Run(run func(record sriracha.RawRecord)) *MockSession_Tokenize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sriracha.RawRecord
		if args[0] != nil {
			arg0 = args[0].(sriracha.RawRecord)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSession_Tokenize_Call) Return(deterministicToken sriracha.DeterministicToken, err error) *MockSession_Tokenize_Call {
	_c.Call.Return(deterministicToken, err)
	return _c
}

func (_c *MockSession_Tokenize_Call) RunAndReturn(run func(record sriracha.RawRecord) (sriracha.DeterministicToken, error)) *MockSession_Tokenize_Call {
	_c.Call.Return(run)
	return _c
}

// TokenizeBloom provides a mock function for the type MockSession
func (_mock *MockSession) TokenizeBloom(record sriracha.RawRecord) (sriracha.BloomToken, error) {
	ret := _mock.Called(record)

	if len(ret) == 0 {
		panic("no return value specified for TokenizeBloom")
	}

	var r0 sriracha.BloomToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(sriracha.RawRecord) (sriracha.BloomToken, error)); ok {
		return returnFunc(record)
	}
	if returnFunc, ok := ret.Get(0).(func(sriracha.RawRecord) sriracha.BloomToken); ok {
		r0 = returnFunc(record)
	} else {
		r0 = ret.Get(0).(sriracha.BloomToken)
	}
	if returnFunc, ok := ret.Get(1).(func(sriracha.RawRecord) error); ok {
		r1 = returnFunc(record)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSession_TokenizeBloom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TokenizeBloom'
type MockSession_TokenizeBloom_Call struct {
	*mock.Call
}

// TokenizeBloom is a helper method to define mock.On call
//   - record sriracha.RawRecord
func (_e *MockSession_Expecter) TokenizeBloom(record interface{}) *MockSession_TokenizeBloom_Call {
	return &MockSession_TokenizeBloom_Call{Call: _e.mock.On("TokenizeBloom", record)}
}

func (_c *MockSession_TokenizeBloom_Call) Run(run func(record sriracha.RawRecord)) *MockSession_TokenizeBloom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sriracha.RawRecord
		if args[0] != nil {
			arg0 = args[0].(sriracha.RawRecord)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSession_TokenizeBloom_Call) Return(bloomToken sriracha.BloomToken, err error) *MockSession_TokenizeBloom_Call {
	_c.Call.Return(bloomToken, err)
	return _c
}

func (_c *MockSession_TokenizeBloom_Call) RunAndReturn(run func(record sriracha.RawRecord) (sriracha.BloomToken, error)) *MockSession_TokenizeBloom_Call {
	_c.Call.Return(run)
	return _c
}

// TokenizeField provides a mock function for the type MockSession
func (_mock *MockSession) TokenizeField(value string, path sriracha.FieldPath) ([]byte, error) {
	ret := _mock.Called(value, path)

	if len(ret) == 0 {
		panic("no return value specified for TokenizeField")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, sriracha.FieldPath) ([]byte, error)); ok {
		return returnFunc(value, path)
	}
	if returnFunc, ok := ret.Get(0).(func(string, sriracha.FieldPath) []byte); ok {
		r0 = returnFunc(value, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, sriracha.FieldPath) error); ok {
		r1 = returnFunc(value, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSession_TokenizeField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TokenizeField'
type MockSession_TokenizeField_Call struct {
	*mock.Call
}

// TokenizeField is a helper method to define mock.On call
//   - value string
//   - path sriracha.FieldPath
func (_e *MockSession_Expecter) TokenizeField(value interface{}, path interface{}) *MockSession_TokenizeField_Call {
	return &MockSession_TokenizeField_Call{Call: _e.mock.On("TokenizeField", value, path)}
}

func (_c *MockSession_TokenizeField_Call) Run(run func(value string, path sriracha.FieldPath)) *MockSession_TokenizeField_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 sriracha.FieldPath
		if args[1] != nil {
			arg1 = args[1].(sriracha.FieldPath)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSession_TokenizeField_Call) Return(bytes []byte, err error) *MockSession_TokenizeField_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockSession_TokenizeField_Call) RunAndReturn(run func(value string, path sriracha.FieldPath) ([]byte, error)) *MockSession_TokenizeField_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRecord provides a mock function for the type MockSession
func (_mock *MockSession) ValidateRecord(record sriracha.RawRecord) []error {
	ret := _mock.Called(record)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRecord")
	}

	var r0 []error
	if returnFunc, ok := ret.Get(0).(func(sriracha.RawRecord) []error); ok {
		r0 = returnFunc(record)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}
	return r0
}

// MockSession_ValidateRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRecord'
type MockSession_ValidateRecord_Call struct {
	*mock.Call
}

// ValidateRecord is a helper method to define mock.On call
//   - record sriracha.RawRecord
func (_e *MockSession_Expecter) ValidateRecord(record interface{}) *MockSession_ValidateRecord_Call {
	return &MockSession_ValidateRecord_Call{Call: _e.mock.On("ValidateRecord", record)}
}

func (_c *MockSession_ValidateRecord_Call) Run(run func(record sriracha.RawRecord)) *MockSession_ValidateRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sriracha.RawRecord
		if args[0] != nil {
			arg0 = args[0].(sriracha.RawRecord)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSession_ValidateRecord_Call) Return(errs []error) *MockSession_ValidateRecord_Call {
	_c.Call.Return(errs)
	return _c
}

func (_c *MockSession_ValidateRecord_Call) RunAndReturn(run func(record sriracha.RawRecord) []error) *MockSession_ValidateRecord_Call {
	_c.Call.Return(run)
	return _c
}
