// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockconsent

import (
	ed25519 "crypto/ed25519"

	mock "github.com/stretchr/testify/mock"
	srirachav1 "go.sriracha.dev/transport/proto/srirachav1"
)

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

type MockValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidator) EXPECT() *MockValidator_Expecter {
	return &MockValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function with given fields: p, peerKey, peerID
func (_m *MockValidator) Validate(p *srirachav1.ConsentPolicy, peerKey ed25519.PublicKey, peerID string) error {
	ret := _m.Called(p, peerKey, peerID)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*srirachav1.ConsentPolicy, ed25519.PublicKey, string) error); ok {
		r0 = rf(p, peerKey, peerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - p *srirachav1.ConsentPolicy
//   - peerKey ed25519.PublicKey
//   - peerID string
func (_e *MockValidator_Expecter) Validate(p interface{}, peerKey interface{}, peerID interface{}) *MockValidator_Validate_Call {
	return &MockValidator_Validate_Call{Call: _e.mock.On("Validate", p, peerKey, peerID)}
}

func (_c *MockValidator_Validate_Call) Run(run func(p *srirachav1.ConsentPolicy, peerKey ed25519.PublicKey, peerID string)) *MockValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*srirachav1.ConsentPolicy), args[1].(ed25519.PublicKey), args[2].(string))
	})
	return _c
}

func (_c *MockValidator_Validate_Call) Return(_a0 error) *MockValidator_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValidator_Validate_Call) RunAndReturn(run func(*srirachav1.ConsentPolicy, ed25519.PublicKey, string) error) *MockValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockValidator creates a new instance of MockValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidator {
	mock := &MockValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
