// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: sriracha.proto

package srirachav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SrirachaService_GetCapabilities_FullMethodName = "/sriracha.v1.SrirachaService/GetCapabilities"
	SrirachaService_Query_FullMethodName           = "/sriracha.v1.SrirachaService/Query"
	SrirachaService_BulkLink_FullMethodName        = "/sriracha.v1.SrirachaService/BulkLink"
)

// SrirachaServiceClient is the client API for SrirachaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SrirachaServiceClient interface {
	GetCapabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	BulkLink(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BulkTokenBatch, BulkMatchResult], error)
}

type srirachaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSrirachaServiceClient(cc grpc.ClientConnInterface) SrirachaServiceClient {
	return &srirachaServiceClient{cc}
}

func (c *srirachaServiceClient) GetCapabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, SrirachaService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srirachaServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, SrirachaService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srirachaServiceClient) BulkLink(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BulkTokenBatch, BulkMatchResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SrirachaService_ServiceDesc.Streams[0], SrirachaService_BulkLink_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BulkTokenBatch, BulkMatchResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SrirachaService_BulkLinkClient = grpc.BidiStreamingClient[BulkTokenBatch, BulkMatchResult]

// SrirachaServiceServer is the server API for SrirachaService service.
// All implementations must embed UnimplementedSrirachaServiceServer
// for forward compatibility.
type SrirachaServiceServer interface {
	GetCapabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	BulkLink(grpc.BidiStreamingServer[BulkTokenBatch, BulkMatchResult]) error
	mustEmbedUnimplementedSrirachaServiceServer()
}

// UnimplementedSrirachaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSrirachaServiceServer struct{}

func (UnimplementedSrirachaServiceServer) GetCapabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedSrirachaServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedSrirachaServiceServer) BulkLink(grpc.BidiStreamingServer[BulkTokenBatch, BulkMatchResult]) error {
	return status.Error(codes.Unimplemented, "method BulkLink not implemented")
}
func (UnimplementedSrirachaServiceServer) mustEmbedUnimplementedSrirachaServiceServer() {}
func (UnimplementedSrirachaServiceServer) testEmbeddedByValue()                         {}

// UnsafeSrirachaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SrirachaServiceServer will
// result in compilation errors.
type UnsafeSrirachaServiceServer interface {
	mustEmbedUnimplementedSrirachaServiceServer()
}

func RegisterSrirachaServiceServer(s grpc.ServiceRegistrar, srv SrirachaServiceServer) {
	// If the following call panics, it indicates UnimplementedSrirachaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SrirachaService_ServiceDesc, srv)
}

func _SrirachaService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrirachaServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SrirachaService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrirachaServiceServer).GetCapabilities(ctx, req.(*CapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrirachaService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrirachaServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SrirachaService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrirachaServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrirachaService_BulkLink_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SrirachaServiceServer).BulkLink(&grpc.GenericServerStream[BulkTokenBatch, BulkMatchResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SrirachaService_BulkLinkServer = grpc.BidiStreamingServer[BulkTokenBatch, BulkMatchResult]

// SrirachaService_ServiceDesc is the grpc.ServiceDesc for SrirachaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SrirachaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sriracha.v1.SrirachaService",
	HandlerType: (*SrirachaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _SrirachaService_GetCapabilities_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _SrirachaService_Query_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BulkLink",
			Handler:       _SrirachaService_BulkLink_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sriracha.proto",
}
