// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sriracha.proto

package srirachav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchStatus int32

const (
	MatchStatus_MATCH_STATUS_UNSPECIFIED MatchStatus = 0
	MatchStatus_MATCHED                  MatchStatus = 1
	MatchStatus_NO_MATCH                 MatchStatus = 2
	MatchStatus_BELOW_THRESHOLD          MatchStatus = 3
	MatchStatus_MULTIPLE_CANDIDATES      MatchStatus = 4
)

// Enum value maps for MatchStatus.
var (
	MatchStatus_name = map[int32]string{
		0: "MATCH_STATUS_UNSPECIFIED",
		1: "MATCHED",
		2: "NO_MATCH",
		3: "BELOW_THRESHOLD",
		4: "MULTIPLE_CANDIDATES",
	}
	MatchStatus_value = map[string]int32{
		"MATCH_STATUS_UNSPECIFIED": 0,
		"MATCHED":                  1,
		"NO_MATCH":                 2,
		"BELOW_THRESHOLD":          3,
		"MULTIPLE_CANDIDATES":      4,
	}
)

func (x MatchStatus) Enum() *MatchStatus {
	p := new(MatchStatus)
	*p = x
	return p
}

func (x MatchStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sriracha_proto_enumTypes[0].Descriptor()
}

func (MatchStatus) Type() protoreflect.EnumType {
	return &file_sriracha_proto_enumTypes[0]
}

func (x MatchStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchStatus.Descriptor instead.
func (MatchStatus) EnumDescriptor() ([]byte, []int) {
	return file_sriracha_proto_rawDescGZIP(), []int{0}
}

type MatchMode int32

const (
	MatchMode_MATCH_MODE_UNSPECIFIED MatchMode = 0
	MatchMode_DETERMINISTIC          MatchMode = 1
	MatchMode_PROBABILISTIC          MatchMode = 2
)

// Enum value maps for MatchMode.
var (
	MatchMode_name = map[int32]string{
		0: "MATCH_MODE_UNSPECIFIED",
		1: "DETERMINISTIC",
		2: "PROBABILISTIC",
	}
	MatchMode_value = map[string]int32{
		"MATCH_MODE_UNSPECIFIED": 0,
		"DETERMINISTIC":          1,
		"PROBABILISTIC":          2,
	}
)

func (x MatchMode) Enum() *MatchMode {
	p := new(MatchMode)
	*p = x
	return p
}

func (x MatchMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchMode) Descriptor() protoreflect.EnumDescriptor {
	return file_sriracha_proto_enumTypes[1].Descriptor()
}

func (MatchMode) Type() protoreflect.EnumType {
	return &file_sriracha_proto_enumTypes[1]
}

func (x MatchMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchMode.Descriptor instead.
func (MatchMode) EnumDescriptor() ([]byte, []int) {
	return file_sriracha_proto_rawDescGZIP(), []int{1}
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_sriracha_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sriracha_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_sriracha_proto_rawDescGZIP(), []int{0}
}

type CapabilitiesResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SpecVersion      string                 `protobuf:"bytes,1,opt,name=spec_version,json=specVersion,proto3" json:"spec_version,omitempty"`
	FieldsetVersions []string               `protobuf:"bytes,2,rep,name=fieldset_versions,json=fieldsetVersions,proto3" json:"fieldset_versions,omitempty"`
	SupportedFields  []string               `protobuf:"bytes,3,rep,name=supported_fields,json=supportedFields,proto3" json:"supported_fields,omitempty"`
	MatchModes       []MatchMode            `protobuf:"varint,4,rep,packed,name=match_modes,json=matchModes,proto3,enum=sriracha.v1.MatchMode" json:"match_modes,omitempty"`
	RateLimits       *RateLimits            `protobuf:"bytes,5,opt,name=rate_limits,json=rateLimits,proto3" json:"rate_limits,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_sriracha_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sriracha_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_sriracha_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilitiesResponse) GetSpecVersion() string {
	if x != nil {
		return x.SpecVersion
	}
	return ""
}

func (x *CapabilitiesResponse) GetFieldsetVersions() []string {
	if x != nil {
		return x.FieldsetVersions
	}
	return nil
}

func (x *CapabilitiesResponse) GetSupportedFields() []string {
	if x != nil {
		return x.SupportedFields
	}
	return nil
}

func (x *CapabilitiesResponse) GetMatchModes() []MatchMode {
	if x != nil {
		return x.MatchModes
	}
	return nil
}

func (x *CapabilitiesResponse) GetRateLimits() *RateLimits {
	if x != nil {
		return x.RateLimits
	}
	return nil
}

type RateLimits struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	QueriesPerMinute  uint32                 `protobuf:"varint,1,opt,name=queries_per_minute,json=queriesPerMinute,proto3" json:"queries_per_minute,omitempty"`
	BulkRecordsPerDay uint32                 `protobuf:"varint,2,opt,name=bulk_records_per_day,json=bulkRecordsPerDay,proto3" json:"bulk_records_per_day,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RateLimits) Reset() {
	*x = RateLimits{}
	mi := &file_sriracha_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimits) ProtoMessage() {}

func (x *RateLimits) ProtoReflect() protoreflect.Message {
	mi := &file_sriracha_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimits.ProtoReflect.Descriptor instead.
func (*RateLimits) Descriptor() ([]byte, []int) {
	return file_sriracha_proto_rawDescGZIP(), []int{2}
}

func (x *RateLimits) GetQueriesPerMinute() uint32 {
	if x != nil {
		return x.QueriesPerMinute
	}
	return 0
}

func (x *RateLimits) GetBulkRecordsPerDay() uint32 {
	if x != nil {
		return x.BulkRecordsPerDay
	}
	return 0
}

type QueryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TokenRecord     []byte                 `protobuf:"bytes,2,opt,name=token_record,json=tokenRecord,proto3" json:"token_record,omitempty"`
	FieldsetVersion string                 `protobuf:"bytes,3,opt,name=fieldset_version,json=fieldsetVersion,proto3" json:"fieldset_version,omitempty"`
	MatchMode       MatchMode              `protobuf:"varint,4,opt,name=match_mode,json=matchMode,proto3,enum=sriracha.v1.MatchMode" json:"match_mode,omitempty"`
	MatchConfig     *MatchConfig           `protobuf:"bytes,5,opt,name=match_config,json=matchConfig,proto3" json:"match_config,omitempty"`
	RequestedFields []string               `protobuf:"bytes,6,rep,name=requested_fields,json=requestedFields,proto3" json:"requested_fields,omitempty"`
	Policy          *ConsentPolicy         `protobuf:"bytes,7,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_sriracha_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sriracha_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_sriracha_proto_rawDescGZIP(), []int{3}
}

func (x *QueryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *QueryRequest) GetTokenRecord() []byte {
	if x != nil {
		return x.TokenRecord
	}
	return nil
}

func (x *QueryRequest) GetFieldsetVersion() string {
	if x != nil {
		return x.FieldsetVersion
	}
	return ""
}

func (x *QueryRequest) GetMatchMode() MatchMode {
	if x != nil {
		return x.MatchMode
	}
	return MatchMode_MATCH_MODE_UNSPECIFIED
}

func (x *QueryRequest) GetMatchConfig() *MatchConfig {
	if x != nil {
		return x.MatchConfig
	}
	return nil
}

func (x *QueryRequest) GetRequestedFields() []string {
	if x != nil {
		return x.RequestedFields
	}
	return nil
}

func (x *QueryRequest) GetPolicy() *ConsentPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Fields        []*FieldValue          `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	NotHeld       []string               `protobuf:"bytes,4,rep,name=not_held,json=notHeld,proto3" json:"not_held,omitempty"`
	NotFound      []string               `protobuf:"bytes,5,rep,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	Status        MatchStatus            `protobuf:"varint,6,opt,name=status,proto3,enum=sriracha.v1.MatchStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_sriracha_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sriracha_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_sriracha_proto_rawDescGZIP(), []int{4}
}

func (x *QueryResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *QueryResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *QueryResponse) GetFields() []*FieldValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *QueryResponse) GetNotHeld() []string {
	if x != nil {
		return x.NotHeld
	}
	return nil
}

func (x *QueryResponse) GetNotFound() []string {
	if x != nil {
		return x.NotFound
	}
	return nil
}

func (x *QueryResponse) GetStatus() MatchStatus {
	if x != nil {
		return x.Status
	}
	return MatchStatus_MATCH_STATUS_UNSPECIFIED
}

type FieldValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldPath     string                 `protobuf:"bytes,1,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldValue) Reset() {
	*x = FieldValue{}
	mi := &file_sriracha_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldValue) ProtoMessage() {}

func (x *FieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_sriracha_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldValue.ProtoReflect.Descriptor instead.
func (*FieldValue) Descriptor() ([]byte, []int) {
	return file_sriracha_proto_rawDescGZIP(), []int{5}
}

func (x *FieldValue) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *FieldValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type BulkTokenBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TokenRecords  [][]byte               `protobuf:"bytes,2,rep,name=token_records,json=tokenRecords,proto3" json:"token_records,omitempty"`
	RecordRefs    []string               `protobuf:"bytes,3,rep,name=record_refs,json=recordRefs,proto3" json:"record_refs,omitempty"`
	Policy        *ConsentPolicy         `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkTokenBatch) Reset() {
	*x = BulkTokenBatch{}
	mi := &file_sriracha_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkTokenBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkTokenBatch) ProtoMessage() {}

func (x *BulkTokenBatch) ProtoReflect() protoreflect.Message {
	mi := &file_sriracha_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkTokenBatch.ProtoReflect.Descriptor instead.
func (*BulkTokenBatch) Descriptor() ([]byte, []int) {
	return file_sriracha_proto_rawDescGZIP(), []int{6}
}

func (x *BulkTokenBatch) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BulkTokenBatch) GetTokenRecords() [][]byte {
	if x != nil {
		return x.TokenRecords
	}
	return nil
}

func (x *BulkTokenBatch) GetRecordRefs() []string {
	if x != nil {
		return x.RecordRefs
	}
	return nil
}

func (x *BulkTokenBatch) GetPolicy() *ConsentPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type BulkMatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Entries       []*MatchResultEntry    `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkMatchResult) Reset() {
	*x = BulkMatchResult{}
	mi := &file_sriracha_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkMatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkMatchResult) ProtoMessage() {}

func (x *BulkMatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_sriracha_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkMatchResult.ProtoReflect.Descriptor instead.
func (*BulkMatchResult) Descriptor() ([]byte, []int) {
	return file_sriracha_proto_rawDescGZIP(), []int{7}
}

func (x *BulkMatchResult) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BulkMatchResult) GetEntries() []*MatchResultEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MatchResultEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordRef     string                 `protobuf:"bytes,1,opt,name=record_ref,json=recordRef,proto3" json:"record_ref,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Fields        []*FieldValue          `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	NotHeld       []string               `protobuf:"bytes,4,rep,name=not_held,json=notHeld,proto3" json:"not_held,omitempty"`
	NotFound      []string               `protobuf:"bytes,5,rep,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	Status        MatchStatus            `protobuf:"varint,6,opt,name=status,proto3,enum=sriracha.v1.MatchStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResultEntry) Reset() {
	*x = MatchResultEntry{}
	mi := &file_sriracha_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResultEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResultEntry) ProtoMessage() {}

func (x *MatchResultEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sriracha_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResultEntry.ProtoReflect.Descriptor instead.
func (*MatchResultEntry) Descriptor() ([]byte, []int) {
	return file_sriracha_proto_rawDescGZIP(), []int{8}
}

func (x *MatchResultEntry) GetRecordRef() string {
	if x != nil {
		return x.RecordRef
	}
	return ""
}

func (x *MatchResultEntry) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *MatchResultEntry) GetFields() []*FieldValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *MatchResultEntry) GetNotHeld() []string {
	if x != nil {
		return x.NotHeld
	}
	return nil
}

func (x *MatchResultEntry) GetNotFound() []string {
	if x != nil {
		return x.NotFound
	}
	return nil
}

func (x *MatchResultEntry) GetStatus() MatchStatus {
	if x != nil {
		return x.Status
	}
	return MatchStatus_MATCH_STATUS_UNSPECIFIED
}

type MatchConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threshold     float32                `protobuf:"fixed32,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
	MaxResults    uint32                 `protobuf:"varint,2,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	FieldWeights  []*FieldWeight         `protobuf:"bytes,3,rep,name=field_weights,json=fieldWeights,proto3" json:"field_weights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchConfig) Reset() {
	*x = MatchConfig{}
	mi := &file_sriracha_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchConfig) ProtoMessage() {}

func (x *MatchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sriracha_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchConfig.ProtoReflect.Descriptor instead.
func (*MatchConfig) Descriptor() ([]byte, []int) {
	return file_sriracha_proto_rawDescGZIP(), []int{9}
}

func (x *MatchConfig) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *MatchConfig) GetMaxResults() uint32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *MatchConfig) GetFieldWeights() []*FieldWeight {
	if x != nil {
		return x.FieldWeights
	}
	return nil
}

type FieldWeight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldPath     string                 `protobuf:"bytes,1,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Weight        float32                `protobuf:"fixed32,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldWeight) Reset() {
	*x = FieldWeight{}
	mi := &file_sriracha_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldWeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldWeight) ProtoMessage() {}

func (x *FieldWeight) ProtoReflect() protoreflect.Message {
	mi := &file_sriracha_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldWeight.ProtoReflect.Descriptor instead.
func (*FieldWeight) Descriptor() ([]byte, []int) {
	return file_sriracha_proto_rawDescGZIP(), []int{10}
}

func (x *FieldWeight) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *FieldWeight) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type ConsentPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssuerId      string                 `protobuf:"bytes,1,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Purpose       string                 `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
	IssuedAt      int64                  `protobuf:"varint,4,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Signature     []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	PolicyId      string                 `protobuf:"bytes,7,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsentPolicy) Reset() {
	*x = ConsentPolicy{}
	mi := &file_sriracha_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsentPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsentPolicy) ProtoMessage() {}

func (x *ConsentPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_sriracha_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsentPolicy.ProtoReflect.Descriptor instead.
func (*ConsentPolicy) Descriptor() ([]byte, []int) {
	return file_sriracha_proto_rawDescGZIP(), []int{11}
}

func (x *ConsentPolicy) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *ConsentPolicy) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ConsentPolicy) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *ConsentPolicy) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *ConsentPolicy) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *ConsentPolicy) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ConsentPolicy) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

// TokenRecord is the wire representation of a tokenised record,
// serialised as the bytes value of QueryRequest.token_record.
type TokenRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FieldsetVersion string                 `protobuf:"bytes,1,opt,name=fieldset_version,json=fieldsetVersion,proto3" json:"fieldset_version,omitempty"`
	Mode            MatchMode              `protobuf:"varint,2,opt,name=mode,proto3,enum=sriracha.v1.MatchMode" json:"mode,omitempty"`
	Algo            string                 `protobuf:"bytes,3,opt,name=algo,proto3" json:"algo,omitempty"`
	Payload         []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Checksum        []byte                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TokenRecord) Reset() {
	*x = TokenRecord{}
	mi := &file_sriracha_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRecord) ProtoMessage() {}

func (x *TokenRecord) ProtoReflect() protoreflect.Message {
	mi := &file_sriracha_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRecord.ProtoReflect.Descriptor instead.
func (*TokenRecord) Descriptor() ([]byte, []int) {
	return file_sriracha_proto_rawDescGZIP(), []int{12}
}

func (x *TokenRecord) GetFieldsetVersion() string {
	if x != nil {
		return x.FieldsetVersion
	}
	return ""
}

func (x *TokenRecord) GetMode() MatchMode {
	if x != nil {
		return x.Mode
	}
	return MatchMode_MATCH_MODE_UNSPECIFIED
}

func (x *TokenRecord) GetAlgo() string {
	if x != nil {
		return x.Algo
	}
	return ""
}

func (x *TokenRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TokenRecord) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

var File_sriracha_proto protoreflect.FileDescriptor

const file_sriracha_proto_rawDesc = "" +
	"\n" +
	"\x0esriracha.proto\x12\vsriracha.v1\"\x15\n" +
	"\x13CapabilitiesRequest\"\x84\x02\n" +
	"\x14CapabilitiesResponse\x12!\n" +
	"\fspec_version\x18\x01 \x01(\tR\vspecVersion\x12+\n" +
	"\x11fieldset_versions\x18\x02 \x03(\tR\x10fieldsetVersions\x12)\n" +
	"\x10supported_fields\x18\x03 \x03(\tR\x0fsupportedFields\x127\n" +
	"\vmatch_modes\x18\x04 \x03(\x0e2\x16.sriracha.v1.MatchModeR\n" +
	"matchModes\x128\n" +
	"\vrate_limits\x18\x05 \x01(\v2\x17.sriracha.v1.RateLimitsR\n" +
	"rateLimits\"k\n" +
	"\n" +
	"RateLimits\x12,\n" +
	"\x12queries_per_minute\x18\x01 \x01(\rR\x10queriesPerMinute\x12/\n" +
	"\x14bulk_records_per_day\x18\x02 \x01(\rR\x11bulkRecordsPerDay\"\xce\x02\n" +
	"\fQueryRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\ftoken_record\x18\x02 \x01(\fR\vtokenRecord\x12)\n" +
	"\x10fieldset_version\x18\x03 \x01(\tR\x0ffieldsetVersion\x125\n" +
	"\n" +
	"match_mode\x18\x04 \x01(\x0e2\x16.sriracha.v1.MatchModeR\tmatchMode\x12;\n" +
	"\fmatch_config\x18\x05 \x01(\v2\x18.sriracha.v1.MatchConfigR\vmatchConfig\x12)\n" +
	"\x10requested_fields\x18\x06 \x03(\tR\x0frequestedFields\x122\n" +
	"\x06policy\x18\a \x01(\v2\x1a.sriracha.v1.ConsentPolicyR\x06policy\"\xe9\x01\n" +
	"\rQueryResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12/\n" +
	"\x06fields\x18\x03 \x03(\v2\x17.sriracha.v1.FieldValueR\x06fields\x12\x19\n" +
	"\bnot_held\x18\x04 \x03(\tR\anotHeld\x12\x1b\n" +
	"\tnot_found\x18\x05 \x03(\tR\bnotFound\x120\n" +
	"\x06status\x18\x06 \x01(\x0e2\x18.sriracha.v1.MatchStatusR\x06status\"A\n" +
	"\n" +
	"FieldValue\x12\x1d\n" +
	"\n" +
	"field_path\x18\x01 \x01(\tR\tfieldPath\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xa9\x01\n" +
	"\x0eBulkTokenBatch\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rtoken_records\x18\x02 \x03(\fR\ftokenRecords\x12\x1f\n" +
	"\vrecord_refs\x18\x03 \x03(\tR\n" +
	"recordRefs\x122\n" +
	"\x06policy\x18\x04 \x01(\v2\x1a.sriracha.v1.ConsentPolicyR\x06policy\"i\n" +
	"\x0fBulkMatchResult\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x127\n" +
	"\aentries\x18\x02 \x03(\v2\x1d.sriracha.v1.MatchResultEntryR\aentries\"\xec\x01\n" +
	"\x10MatchResultEntry\x12\x1d\n" +
	"\n" +
	"record_ref\x18\x01 \x01(\tR\trecordRef\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12/\n" +
	"\x06fields\x18\x03 \x03(\v2\x17.sriracha.v1.FieldValueR\x06fields\x12\x19\n" +
	"\bnot_held\x18\x04 \x03(\tR\anotHeld\x12\x1b\n" +
	"\tnot_found\x18\x05 \x03(\tR\bnotFound\x120\n" +
	"\x06status\x18\x06 \x01(\x0e2\x18.sriracha.v1.MatchStatusR\x06status\"\x8b\x01\n" +
	"\vMatchConfig\x12\x1c\n" +
	"\tthreshold\x18\x01 \x01(\x02R\tthreshold\x12\x1f\n" +
	"\vmax_results\x18\x02 \x01(\rR\n" +
	"maxResults\x12=\n" +
	"\rfield_weights\x18\x03 \x03(\v2\x18.sriracha.v1.FieldWeightR\ffieldWeights\"D\n" +
	"\vFieldWeight\x12\x1d\n" +
	"\n" +
	"field_path\x18\x01 \x01(\tR\tfieldPath\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x02R\x06weight\"\xda\x01\n" +
	"\rConsentPolicy\x12\x1b\n" +
	"\tissuer_id\x18\x01 \x01(\tR\bissuerId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x18\n" +
	"\apurpose\x18\x03 \x01(\tR\apurpose\x12\x1b\n" +
	"\tissued_at\x18\x04 \x01(\x03R\bissuedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\x12\x1b\n" +
	"\tpolicy_id\x18\a \x01(\tR\bpolicyId\"\xae\x01\n" +
	"\vTokenRecord\x12)\n" +
	"\x10fieldset_version\x18\x01 \x01(\tR\x0ffieldsetVersion\x12*\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x16.sriracha.v1.MatchModeR\x04mode\x12\x12\n" +
	"\x04algo\x18\x03 \x01(\tR\x04algo\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\fR\bchecksum*t\n" +
	"\vMatchStatus\x12\x1c\n" +
	"\x18MATCH_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aMATCHED\x10\x01\x12\f\n" +
	"\bNO_MATCH\x10\x02\x12\x13\n" +
	"\x0fBELOW_THRESHOLD\x10\x03\x12\x17\n" +
	"\x13MULTIPLE_CANDIDATES\x10\x04*M\n" +
	"\tMatchMode\x12\x1a\n" +
	"\x16MATCH_MODE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rDETERMINISTIC\x10\x01\x12\x11\n" +
	"\rPROBABILISTIC\x10\x022\xf4\x01\n" +
	"\x0fSrirachaService\x12V\n" +
	"\x0fGetCapabilities\x12 .sriracha.v1.CapabilitiesRequest\x1a!.sriracha.v1.CapabilitiesResponse\x12>\n" +
	"\x05Query\x12\x19.sriracha.v1.QueryRequest\x1a\x1a.sriracha.v1.QueryResponse\x12I\n" +
	"\bBulkLink\x12\x1b.sriracha.v1.BulkTokenBatch\x1a\x1c.sriracha.v1.BulkMatchResult(\x010\x01B7Z5go.sriracha.dev/transport/proto/srirachav1;srirachav1b\x06proto3"

var (
	file_sriracha_proto_rawDescOnce sync.Once
	file_sriracha_proto_rawDescData []byte
)

func file_sriracha_proto_rawDescGZIP() []byte {
	file_sriracha_proto_rawDescOnce.Do(func() {
		file_sriracha_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sriracha_proto_rawDesc), len(file_sriracha_proto_rawDesc)))
	})
	return file_sriracha_proto_rawDescData
}

var file_sriracha_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sriracha_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_sriracha_proto_goTypes = []any{
	(MatchStatus)(0),             // 0: sriracha.v1.MatchStatus
	(MatchMode)(0),               // 1: sriracha.v1.MatchMode
	(*CapabilitiesRequest)(nil),  // 2: sriracha.v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil), // 3: sriracha.v1.CapabilitiesResponse
	(*RateLimits)(nil),           // 4: sriracha.v1.RateLimits
	(*QueryRequest)(nil),         // 5: sriracha.v1.QueryRequest
	(*QueryResponse)(nil),        // 6: sriracha.v1.QueryResponse
	(*FieldValue)(nil),           // 7: sriracha.v1.FieldValue
	(*BulkTokenBatch)(nil),       // 8: sriracha.v1.BulkTokenBatch
	(*BulkMatchResult)(nil),      // 9: sriracha.v1.BulkMatchResult
	(*MatchResultEntry)(nil),     // 10: sriracha.v1.MatchResultEntry
	(*MatchConfig)(nil),          // 11: sriracha.v1.MatchConfig
	(*FieldWeight)(nil),          // 12: sriracha.v1.FieldWeight
	(*ConsentPolicy)(nil),        // 13: sriracha.v1.ConsentPolicy
	(*TokenRecord)(nil),          // 14: sriracha.v1.TokenRecord
}
var file_sriracha_proto_depIdxs = []int32{
	1,  // 0: sriracha.v1.CapabilitiesResponse.match_modes:type_name -> sriracha.v1.MatchMode
	4,  // 1: sriracha.v1.CapabilitiesResponse.rate_limits:type_name -> sriracha.v1.RateLimits
	1,  // 2: sriracha.v1.QueryRequest.match_mode:type_name -> sriracha.v1.MatchMode
	11, // 3: sriracha.v1.QueryRequest.match_config:type_name -> sriracha.v1.MatchConfig
	13, // 4: sriracha.v1.QueryRequest.policy:type_name -> sriracha.v1.ConsentPolicy
	7,  // 5: sriracha.v1.QueryResponse.fields:type_name -> sriracha.v1.FieldValue
	0,  // 6: sriracha.v1.QueryResponse.status:type_name -> sriracha.v1.MatchStatus
	13, // 7: sriracha.v1.BulkTokenBatch.policy:type_name -> sriracha.v1.ConsentPolicy
	10, // 8: sriracha.v1.BulkMatchResult.entries:type_name -> sriracha.v1.MatchResultEntry
	7,  // 9: sriracha.v1.MatchResultEntry.fields:type_name -> sriracha.v1.FieldValue
	0,  // 10: sriracha.v1.MatchResultEntry.status:type_name -> sriracha.v1.MatchStatus
	12, // 11: sriracha.v1.MatchConfig.field_weights:type_name -> sriracha.v1.FieldWeight
	1,  // 12: sriracha.v1.TokenRecord.mode:type_name -> sriracha.v1.MatchMode
	2,  // 13: sriracha.v1.SrirachaService.GetCapabilities:input_type -> sriracha.v1.CapabilitiesRequest
	5,  // 14: sriracha.v1.SrirachaService.Query:input_type -> sriracha.v1.QueryRequest
	8,  // 15: sriracha.v1.SrirachaService.BulkLink:input_type -> sriracha.v1.BulkTokenBatch
	3,  // 16: sriracha.v1.SrirachaService.GetCapabilities:output_type -> sriracha.v1.CapabilitiesResponse
	6,  // 17: sriracha.v1.SrirachaService.Query:output_type -> sriracha.v1.QueryResponse
	9,  // 18: sriracha.v1.SrirachaService.BulkLink:output_type -> sriracha.v1.BulkMatchResult
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_sriracha_proto_init() }
func file_sriracha_proto_init() {
	if File_sriracha_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sriracha_proto_rawDesc), len(file_sriracha_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sriracha_proto_goTypes,
		DependencyIndexes: file_sriracha_proto_depIdxs,
		EnumInfos:         file_sriracha_proto_enumTypes,
		MessageInfos:      file_sriracha_proto_msgTypes,
	}.Build()
	File_sriracha_proto = out.File
	file_sriracha_proto_goTypes = nil
	file_sriracha_proto_depIdxs = nil
}
