// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksrirachav1

import (
	context "context"

	metadata "google.golang.org/grpc/metadata"

	mock "github.com/stretchr/testify/mock"

	srirachav1 "go.sriracha.dev/transport/proto/srirachav1"
)

// MockSrirachaService_BulkLinkServer is an autogenerated mock type for the SrirachaService_BulkLinkServer type
type MockSrirachaService_BulkLinkServer[Req interface{}, Res interface{}] struct {
	mock.Mock
}

type MockSrirachaService_BulkLinkServer_Expecter[Req interface{}, Res interface{}] struct {
	mock *mock.Mock
}

func (_m *MockSrirachaService_BulkLinkServer[Req, Res]) EXPECT() *MockSrirachaService_BulkLinkServer_Expecter[Req, Res] {
	return &MockSrirachaService_BulkLinkServer_Expecter[Req, Res]{mock: &_m.Mock}
}

// Context provides a mock function with no fields
func (_m *MockSrirachaService_BulkLinkServer[Req, Res]) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// MockSrirachaService_BulkLinkServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockSrirachaService_BulkLinkServer_Context_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockSrirachaService_BulkLinkServer_Expecter[Req, Res]) Context() *MockSrirachaService_BulkLinkServer_Context_Call[Req, Res] {
	return &MockSrirachaService_BulkLinkServer_Context_Call[Req, Res]{Call: _e.mock.On("Context")}
}

func (_c *MockSrirachaService_BulkLinkServer_Context_Call[Req, Res]) Run(run func()) *MockSrirachaService_BulkLinkServer_Context_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSrirachaService_BulkLinkServer_Context_Call[Req, Res]) Return(_a0 context.Context) *MockSrirachaService_BulkLinkServer_Context_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSrirachaService_BulkLinkServer_Context_Call[Req, Res]) RunAndReturn(run func() context.Context) *MockSrirachaService_BulkLinkServer_Context_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function with no fields
func (_m *MockSrirachaService_BulkLinkServer[Req, Res]) Recv() (*srirachav1.BulkTokenBatch, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *srirachav1.BulkTokenBatch
	var r1 error
	if rf, ok := ret.Get(0).(func() (*srirachav1.BulkTokenBatch, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *srirachav1.BulkTokenBatch); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*srirachav1.BulkTokenBatch)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSrirachaService_BulkLinkServer_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type MockSrirachaService_BulkLinkServer_Recv_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *MockSrirachaService_BulkLinkServer_Expecter[Req, Res]) Recv() *MockSrirachaService_BulkLinkServer_Recv_Call[Req, Res] {
	return &MockSrirachaService_BulkLinkServer_Recv_Call[Req, Res]{Call: _e.mock.On("Recv")}
}

func (_c *MockSrirachaService_BulkLinkServer_Recv_Call[Req, Res]) Run(run func()) *MockSrirachaService_BulkLinkServer_Recv_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSrirachaService_BulkLinkServer_Recv_Call[Req, Res]) Return(_a0 *srirachav1.BulkTokenBatch, _a1 error) *MockSrirachaService_BulkLinkServer_Recv_Call[Req, Res] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSrirachaService_BulkLinkServer_Recv_Call[Req, Res]) RunAndReturn(run func() (*srirachav1.BulkTokenBatch, error)) *MockSrirachaService_BulkLinkServer_Recv_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *MockSrirachaService_BulkLinkServer[Req, Res]) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSrirachaService_BulkLinkServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockSrirachaService_BulkLinkServer_RecvMsg_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *MockSrirachaService_BulkLinkServer_Expecter[Req, Res]) RecvMsg(m interface{}) *MockSrirachaService_BulkLinkServer_RecvMsg_Call[Req, Res] {
	return &MockSrirachaService_BulkLinkServer_RecvMsg_Call[Req, Res]{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockSrirachaService_BulkLinkServer_RecvMsg_Call[Req, Res]) Run(run func(m interface{})) *MockSrirachaService_BulkLinkServer_RecvMsg_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockSrirachaService_BulkLinkServer_RecvMsg_Call[Req, Res]) Return(_a0 error) *MockSrirachaService_BulkLinkServer_RecvMsg_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSrirachaService_BulkLinkServer_RecvMsg_Call[Req, Res]) RunAndReturn(run func(interface{}) error) *MockSrirachaService_BulkLinkServer_RecvMsg_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *MockSrirachaService_BulkLinkServer[Req, Res]) Send(_a0 *srirachav1.BulkMatchResult) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*srirachav1.BulkMatchResult) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSrirachaService_BulkLinkServer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockSrirachaService_BulkLinkServer_Send_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *srirachav1.BulkMatchResult
func (_e *MockSrirachaService_BulkLinkServer_Expecter[Req, Res]) Send(_a0 interface{}) *MockSrirachaService_BulkLinkServer_Send_Call[Req, Res] {
	return &MockSrirachaService_BulkLinkServer_Send_Call[Req, Res]{Call: _e.mock.On("Send", _a0)}
}

func (_c *MockSrirachaService_BulkLinkServer_Send_Call[Req, Res]) Run(run func(_a0 *srirachav1.BulkMatchResult)) *MockSrirachaService_BulkLinkServer_Send_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*srirachav1.BulkMatchResult))
	})
	return _c
}

func (_c *MockSrirachaService_BulkLinkServer_Send_Call[Req, Res]) Return(_a0 error) *MockSrirachaService_BulkLinkServer_Send_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSrirachaService_BulkLinkServer_Send_Call[Req, Res]) RunAndReturn(run func(*srirachav1.BulkMatchResult) error) *MockSrirachaService_BulkLinkServer_Send_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function with given fields: _a0
func (_m *MockSrirachaService_BulkLinkServer[Req, Res]) SendHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSrirachaService_BulkLinkServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type MockSrirachaService_BulkLinkServer_SendHeader_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *MockSrirachaService_BulkLinkServer_Expecter[Req, Res]) SendHeader(_a0 interface{}) *MockSrirachaService_BulkLinkServer_SendHeader_Call[Req, Res] {
	return &MockSrirachaService_BulkLinkServer_SendHeader_Call[Req, Res]{Call: _e.mock.On("SendHeader", _a0)}
}

func (_c *MockSrirachaService_BulkLinkServer_SendHeader_Call[Req, Res]) Run(run func(_a0 metadata.MD)) *MockSrirachaService_BulkLinkServer_SendHeader_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockSrirachaService_BulkLinkServer_SendHeader_Call[Req, Res]) Return(_a0 error) *MockSrirachaService_BulkLinkServer_SendHeader_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSrirachaService_BulkLinkServer_SendHeader_Call[Req, Res]) RunAndReturn(run func(metadata.MD) error) *MockSrirachaService_BulkLinkServer_SendHeader_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *MockSrirachaService_BulkLinkServer[Req, Res]) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSrirachaService_BulkLinkServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockSrirachaService_BulkLinkServer_SendMsg_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *MockSrirachaService_BulkLinkServer_Expecter[Req, Res]) SendMsg(m interface{}) *MockSrirachaService_BulkLinkServer_SendMsg_Call[Req, Res] {
	return &MockSrirachaService_BulkLinkServer_SendMsg_Call[Req, Res]{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockSrirachaService_BulkLinkServer_SendMsg_Call[Req, Res]) Run(run func(m interface{})) *MockSrirachaService_BulkLinkServer_SendMsg_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockSrirachaService_BulkLinkServer_SendMsg_Call[Req, Res]) Return(_a0 error) *MockSrirachaService_BulkLinkServer_SendMsg_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSrirachaService_BulkLinkServer_SendMsg_Call[Req, Res]) RunAndReturn(run func(interface{}) error) *MockSrirachaService_BulkLinkServer_SendMsg_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function with given fields: _a0
func (_m *MockSrirachaService_BulkLinkServer[Req, Res]) SetHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSrirachaService_BulkLinkServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type MockSrirachaService_BulkLinkServer_SetHeader_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *MockSrirachaService_BulkLinkServer_Expecter[Req, Res]) SetHeader(_a0 interface{}) *MockSrirachaService_BulkLinkServer_SetHeader_Call[Req, Res] {
	return &MockSrirachaService_BulkLinkServer_SetHeader_Call[Req, Res]{Call: _e.mock.On("SetHeader", _a0)}
}

func (_c *MockSrirachaService_BulkLinkServer_SetHeader_Call[Req, Res]) Run(run func(_a0 metadata.MD)) *MockSrirachaService_BulkLinkServer_SetHeader_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockSrirachaService_BulkLinkServer_SetHeader_Call[Req, Res]) Return(_a0 error) *MockSrirachaService_BulkLinkServer_SetHeader_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSrirachaService_BulkLinkServer_SetHeader_Call[Req, Res]) RunAndReturn(run func(metadata.MD) error) *MockSrirachaService_BulkLinkServer_SetHeader_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function with given fields: _a0
func (_m *MockSrirachaService_BulkLinkServer[Req, Res]) SetTrailer(_a0 metadata.MD) {
	_m.Called(_a0)
}

// MockSrirachaService_BulkLinkServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type MockSrirachaService_BulkLinkServer_SetTrailer_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *MockSrirachaService_BulkLinkServer_Expecter[Req, Res]) SetTrailer(_a0 interface{}) *MockSrirachaService_BulkLinkServer_SetTrailer_Call[Req, Res] {
	return &MockSrirachaService_BulkLinkServer_SetTrailer_Call[Req, Res]{Call: _e.mock.On("SetTrailer", _a0)}
}

func (_c *MockSrirachaService_BulkLinkServer_SetTrailer_Call[Req, Res]) Run(run func(_a0 metadata.MD)) *MockSrirachaService_BulkLinkServer_SetTrailer_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockSrirachaService_BulkLinkServer_SetTrailer_Call[Req, Res]) Return() *MockSrirachaService_BulkLinkServer_SetTrailer_Call[Req, Res] {
	_c.Call.Return()
	return _c
}

func (_c *MockSrirachaService_BulkLinkServer_SetTrailer_Call[Req, Res]) RunAndReturn(run func(metadata.MD)) *MockSrirachaService_BulkLinkServer_SetTrailer_Call[Req, Res] {
	_c.Run(run)
	return _c
}

// NewMockSrirachaService_BulkLinkServer creates a new instance of MockSrirachaService_BulkLinkServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSrirachaService_BulkLinkServer[Req interface{}, Res interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSrirachaService_BulkLinkServer[Req, Res] {
	mock := &MockSrirachaService_BulkLinkServer[Req, Res]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
