// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksrirachav1

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	srirachav1 "go.sriracha.dev/transport/proto/srirachav1"
)

// MockSrirachaServiceClient is an autogenerated mock type for the SrirachaServiceClient type
type MockSrirachaServiceClient struct {
	mock.Mock
}

type MockSrirachaServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSrirachaServiceClient) EXPECT() *MockSrirachaServiceClient_Expecter {
	return &MockSrirachaServiceClient_Expecter{mock: &_m.Mock}
}

// BulkLink provides a mock function with given fields: ctx, opts
func (_m *MockSrirachaServiceClient) BulkLink(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[srirachav1.BulkTokenBatch, srirachav1.BulkMatchResult], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for BulkLink")
	}

	var r0 grpc.BidiStreamingClient[srirachav1.BulkTokenBatch, srirachav1.BulkMatchResult]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) (grpc.BidiStreamingClient[srirachav1.BulkTokenBatch, srirachav1.BulkMatchResult], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) grpc.BidiStreamingClient[srirachav1.BulkTokenBatch, srirachav1.BulkMatchResult]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.BidiStreamingClient[srirachav1.BulkTokenBatch, srirachav1.BulkMatchResult])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSrirachaServiceClient_BulkLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkLink'
type MockSrirachaServiceClient_BulkLink_Call struct {
	*mock.Call
}

// BulkLink is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...grpc.CallOption
func (_e *MockSrirachaServiceClient_Expecter) BulkLink(ctx interface{}, opts ...interface{}) *MockSrirachaServiceClient_BulkLink_Call {
	return &MockSrirachaServiceClient_BulkLink_Call{Call: _e.mock.On("BulkLink",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockSrirachaServiceClient_BulkLink_Call) Run(run func(ctx context.Context, opts ...grpc.CallOption)) *MockSrirachaServiceClient_BulkLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockSrirachaServiceClient_BulkLink_Call) Return(_a0 grpc.BidiStreamingClient[srirachav1.BulkTokenBatch, srirachav1.BulkMatchResult], _a1 error) *MockSrirachaServiceClient_BulkLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSrirachaServiceClient_BulkLink_Call) RunAndReturn(run func(context.Context, ...grpc.CallOption) (grpc.BidiStreamingClient[srirachav1.BulkTokenBatch, srirachav1.BulkMatchResult], error)) *MockSrirachaServiceClient_BulkLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetCapabilities provides a mock function with given fields: ctx, in, opts
func (_m *MockSrirachaServiceClient) GetCapabilities(ctx context.Context, in *srirachav1.CapabilitiesRequest, opts ...grpc.CallOption) (*srirachav1.CapabilitiesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetCapabilities")
	}

	var r0 *srirachav1.CapabilitiesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *srirachav1.CapabilitiesRequest, ...grpc.CallOption) (*srirachav1.CapabilitiesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *srirachav1.CapabilitiesRequest, ...grpc.CallOption) *srirachav1.CapabilitiesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*srirachav1.CapabilitiesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *srirachav1.CapabilitiesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSrirachaServiceClient_GetCapabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCapabilities'
type MockSrirachaServiceClient_GetCapabilities_Call struct {
	*mock.Call
}

// GetCapabilities is a helper method to define mock.On call
//   - ctx context.Context
//   - in *srirachav1.CapabilitiesRequest
//   - opts ...grpc.CallOption
func (_e *MockSrirachaServiceClient_Expecter) GetCapabilities(ctx interface{}, in interface{}, opts ...interface{}) *MockSrirachaServiceClient_GetCapabilities_Call {
	return &MockSrirachaServiceClient_GetCapabilities_Call{Call: _e.mock.On("GetCapabilities",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockSrirachaServiceClient_GetCapabilities_Call) Run(run func(ctx context.Context, in *srirachav1.CapabilitiesRequest, opts ...grpc.CallOption)) *MockSrirachaServiceClient_GetCapabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*srirachav1.CapabilitiesRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockSrirachaServiceClient_GetCapabilities_Call) Return(_a0 *srirachav1.CapabilitiesResponse, _a1 error) *MockSrirachaServiceClient_GetCapabilities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSrirachaServiceClient_GetCapabilities_Call) RunAndReturn(run func(context.Context, *srirachav1.CapabilitiesRequest, ...grpc.CallOption) (*srirachav1.CapabilitiesResponse, error)) *MockSrirachaServiceClient_GetCapabilities_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: ctx, in, opts
func (_m *MockSrirachaServiceClient) Query(ctx context.Context, in *srirachav1.QueryRequest, opts ...grpc.CallOption) (*srirachav1.QueryResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *srirachav1.QueryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *srirachav1.QueryRequest, ...grpc.CallOption) (*srirachav1.QueryResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *srirachav1.QueryRequest, ...grpc.CallOption) *srirachav1.QueryResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*srirachav1.QueryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *srirachav1.QueryRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSrirachaServiceClient_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockSrirachaServiceClient_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - in *srirachav1.QueryRequest
//   - opts ...grpc.CallOption
func (_e *MockSrirachaServiceClient_Expecter) Query(ctx interface{}, in interface{}, opts ...interface{}) *MockSrirachaServiceClient_Query_Call {
	return &MockSrirachaServiceClient_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockSrirachaServiceClient_Query_Call) Run(run func(ctx context.Context, in *srirachav1.QueryRequest, opts ...grpc.CallOption)) *MockSrirachaServiceClient_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*srirachav1.QueryRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockSrirachaServiceClient_Query_Call) Return(_a0 *srirachav1.QueryResponse, _a1 error) *MockSrirachaServiceClient_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSrirachaServiceClient_Query_Call) RunAndReturn(run func(context.Context, *srirachav1.QueryRequest, ...grpc.CallOption) (*srirachav1.QueryResponse, error)) *MockSrirachaServiceClient_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSrirachaServiceClient creates a new instance of MockSrirachaServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSrirachaServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSrirachaServiceClient {
	mock := &MockSrirachaServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
