// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksrirachav1

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	srirachav1 "go.sriracha.dev/transport/proto/srirachav1"
)

// MockSrirachaServiceServer is an autogenerated mock type for the SrirachaServiceServer type
type MockSrirachaServiceServer struct {
	mock.Mock
}

type MockSrirachaServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSrirachaServiceServer) EXPECT() *MockSrirachaServiceServer_Expecter {
	return &MockSrirachaServiceServer_Expecter{mock: &_m.Mock}
}

// BulkLink provides a mock function with given fields: _a0
func (_m *MockSrirachaServiceServer) BulkLink(_a0 grpc.BidiStreamingServer[srirachav1.BulkTokenBatch, srirachav1.BulkMatchResult]) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for BulkLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(grpc.BidiStreamingServer[srirachav1.BulkTokenBatch, srirachav1.BulkMatchResult]) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSrirachaServiceServer_BulkLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkLink'
type MockSrirachaServiceServer_BulkLink_Call struct {
	*mock.Call
}

// BulkLink is a helper method to define mock.On call
//   - _a0 grpc.BidiStreamingServer[srirachav1.BulkTokenBatch,srirachav1.BulkMatchResult]
func (_e *MockSrirachaServiceServer_Expecter) BulkLink(_a0 interface{}) *MockSrirachaServiceServer_BulkLink_Call {
	return &MockSrirachaServiceServer_BulkLink_Call{Call: _e.mock.On("BulkLink", _a0)}
}

func (_c *MockSrirachaServiceServer_BulkLink_Call) Run(run func(_a0 grpc.BidiStreamingServer[srirachav1.BulkTokenBatch, srirachav1.BulkMatchResult])) *MockSrirachaServiceServer_BulkLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(grpc.BidiStreamingServer[srirachav1.BulkTokenBatch, srirachav1.BulkMatchResult]))
	})
	return _c
}

func (_c *MockSrirachaServiceServer_BulkLink_Call) Return(_a0 error) *MockSrirachaServiceServer_BulkLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSrirachaServiceServer_BulkLink_Call) RunAndReturn(run func(grpc.BidiStreamingServer[srirachav1.BulkTokenBatch, srirachav1.BulkMatchResult]) error) *MockSrirachaServiceServer_BulkLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetCapabilities provides a mock function with given fields: _a0, _a1
func (_m *MockSrirachaServiceServer) GetCapabilities(_a0 context.Context, _a1 *srirachav1.CapabilitiesRequest) (*srirachav1.CapabilitiesResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetCapabilities")
	}

	var r0 *srirachav1.CapabilitiesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *srirachav1.CapabilitiesRequest) (*srirachav1.CapabilitiesResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *srirachav1.CapabilitiesRequest) *srirachav1.CapabilitiesResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*srirachav1.CapabilitiesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *srirachav1.CapabilitiesRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSrirachaServiceServer_GetCapabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCapabilities'
type MockSrirachaServiceServer_GetCapabilities_Call struct {
	*mock.Call
}

// GetCapabilities is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *srirachav1.CapabilitiesRequest
func (_e *MockSrirachaServiceServer_Expecter) GetCapabilities(_a0 interface{}, _a1 interface{}) *MockSrirachaServiceServer_GetCapabilities_Call {
	return &MockSrirachaServiceServer_GetCapabilities_Call{Call: _e.mock.On("GetCapabilities", _a0, _a1)}
}

func (_c *MockSrirachaServiceServer_GetCapabilities_Call) Run(run func(_a0 context.Context, _a1 *srirachav1.CapabilitiesRequest)) *MockSrirachaServiceServer_GetCapabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*srirachav1.CapabilitiesRequest))
	})
	return _c
}

func (_c *MockSrirachaServiceServer_GetCapabilities_Call) Return(_a0 *srirachav1.CapabilitiesResponse, _a1 error) *MockSrirachaServiceServer_GetCapabilities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSrirachaServiceServer_GetCapabilities_Call) RunAndReturn(run func(context.Context, *srirachav1.CapabilitiesRequest) (*srirachav1.CapabilitiesResponse, error)) *MockSrirachaServiceServer_GetCapabilities_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: _a0, _a1
func (_m *MockSrirachaServiceServer) Query(_a0 context.Context, _a1 *srirachav1.QueryRequest) (*srirachav1.QueryResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *srirachav1.QueryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *srirachav1.QueryRequest) (*srirachav1.QueryResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *srirachav1.QueryRequest) *srirachav1.QueryResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*srirachav1.QueryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *srirachav1.QueryRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSrirachaServiceServer_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockSrirachaServiceServer_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *srirachav1.QueryRequest
func (_e *MockSrirachaServiceServer_Expecter) Query(_a0 interface{}, _a1 interface{}) *MockSrirachaServiceServer_Query_Call {
	return &MockSrirachaServiceServer_Query_Call{Call: _e.mock.On("Query", _a0, _a1)}
}

func (_c *MockSrirachaServiceServer_Query_Call) Run(run func(_a0 context.Context, _a1 *srirachav1.QueryRequest)) *MockSrirachaServiceServer_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*srirachav1.QueryRequest))
	})
	return _c
}

func (_c *MockSrirachaServiceServer_Query_Call) Return(_a0 *srirachav1.QueryResponse, _a1 error) *MockSrirachaServiceServer_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSrirachaServiceServer_Query_Call) RunAndReturn(run func(context.Context, *srirachav1.QueryRequest) (*srirachav1.QueryResponse, error)) *MockSrirachaServiceServer_Query_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedSrirachaServiceServer provides a mock function with no fields
func (_m *MockSrirachaServiceServer) mustEmbedUnimplementedSrirachaServiceServer() {
	_m.Called()
}

// MockSrirachaServiceServer_mustEmbedUnimplementedSrirachaServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedSrirachaServiceServer'
type MockSrirachaServiceServer_mustEmbedUnimplementedSrirachaServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedSrirachaServiceServer is a helper method to define mock.On call
func (_e *MockSrirachaServiceServer_Expecter) mustEmbedUnimplementedSrirachaServiceServer() *MockSrirachaServiceServer_mustEmbedUnimplementedSrirachaServiceServer_Call {
	return &MockSrirachaServiceServer_mustEmbedUnimplementedSrirachaServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedSrirachaServiceServer")}
}

func (_c *MockSrirachaServiceServer_mustEmbedUnimplementedSrirachaServiceServer_Call) Run(run func()) *MockSrirachaServiceServer_mustEmbedUnimplementedSrirachaServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSrirachaServiceServer_mustEmbedUnimplementedSrirachaServiceServer_Call) Return() *MockSrirachaServiceServer_mustEmbedUnimplementedSrirachaServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSrirachaServiceServer_mustEmbedUnimplementedSrirachaServiceServer_Call) RunAndReturn(run func()) *MockSrirachaServiceServer_mustEmbedUnimplementedSrirachaServiceServer_Call {
	_c.Run(run)
	return _c
}

// NewMockSrirachaServiceServer creates a new instance of MockSrirachaServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSrirachaServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSrirachaServiceServer {
	mock := &MockSrirachaServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
