// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocksrirachav1

import mock "github.com/stretchr/testify/mock"

// MockUnsafeSrirachaServiceServer is an autogenerated mock type for the UnsafeSrirachaServiceServer type
type MockUnsafeSrirachaServiceServer struct {
	mock.Mock
}

type MockUnsafeSrirachaServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeSrirachaServiceServer) EXPECT() *MockUnsafeSrirachaServiceServer_Expecter {
	return &MockUnsafeSrirachaServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedSrirachaServiceServer provides a mock function with no fields
func (_m *MockUnsafeSrirachaServiceServer) mustEmbedUnimplementedSrirachaServiceServer() {
	_m.Called()
}

// MockUnsafeSrirachaServiceServer_mustEmbedUnimplementedSrirachaServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedSrirachaServiceServer'
type MockUnsafeSrirachaServiceServer_mustEmbedUnimplementedSrirachaServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedSrirachaServiceServer is a helper method to define mock.On call
func (_e *MockUnsafeSrirachaServiceServer_Expecter) mustEmbedUnimplementedSrirachaServiceServer() *MockUnsafeSrirachaServiceServer_mustEmbedUnimplementedSrirachaServiceServer_Call {
	return &MockUnsafeSrirachaServiceServer_mustEmbedUnimplementedSrirachaServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedSrirachaServiceServer")}
}

func (_c *MockUnsafeSrirachaServiceServer_mustEmbedUnimplementedSrirachaServiceServer_Call) Run(run func()) *MockUnsafeSrirachaServiceServer_mustEmbedUnimplementedSrirachaServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeSrirachaServiceServer_mustEmbedUnimplementedSrirachaServiceServer_Call) Return() *MockUnsafeSrirachaServiceServer_mustEmbedUnimplementedSrirachaServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeSrirachaServiceServer_mustEmbedUnimplementedSrirachaServiceServer_Call) RunAndReturn(run func()) *MockUnsafeSrirachaServiceServer_mustEmbedUnimplementedSrirachaServiceServer_Call {
	_c.Run(run)
	return _c
}

// NewMockUnsafeSrirachaServiceServer creates a new instance of MockUnsafeSrirachaServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeSrirachaServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeSrirachaServiceServer {
	mock := &MockUnsafeSrirachaServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
