// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocktoken

import (
	"github.com/ccuetoh/sriracha"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenizer creates a new instance of MockTokenizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenizer {
	mock := &MockTokenizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenizer is an autogenerated mock type for the Tokenizer type
type MockTokenizer struct {
	mock.Mock
}

type MockTokenizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenizer) EXPECT() *MockTokenizer_Expecter {
	return &MockTokenizer_Expecter{mock: &_m.Mock}
}

// Destroy provides a mock function for the type MockTokenizer
func (_mock *MockTokenizer) Destroy() {
	_mock.Called()
	return
}

// MockTokenizer_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockTokenizer_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
func (_e *MockTokenizer_Expecter) Destroy() *MockTokenizer_Destroy_Call {
	return &MockTokenizer_Destroy_Call{Call: _e.mock.On("Destroy")}
}

func (_c *MockTokenizer_Destroy_Call) Run(run func()) *MockTokenizer_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenizer_Destroy_Call) Return() *MockTokenizer_Destroy_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTokenizer_Destroy_Call) RunAndReturn(run func()) *MockTokenizer_Destroy_Call {
	_c.Run(run)
	return _c
}

// TokenizeDeterministic provides a mock function for the type MockTokenizer
func (_mock *MockTokenizer) TokenizeDeterministic(record sriracha.RawRecord, fs sriracha.FieldSet) (sriracha.DeterministicToken, error) {
	ret := _mock.Called(record, fs)

	if len(ret) == 0 {
		panic("no return value specified for TokenizeDeterministic")
	}

	var r0 sriracha.DeterministicToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(sriracha.RawRecord, sriracha.FieldSet) (sriracha.DeterministicToken, error)); ok {
		return returnFunc(record, fs)
	}
	if returnFunc, ok := ret.Get(0).(func(sriracha.RawRecord, sriracha.FieldSet) sriracha.DeterministicToken); ok {
		r0 = returnFunc(record, fs)
	} else {
		r0 = ret.Get(0).(sriracha.DeterministicToken)
	}
	if returnFunc, ok := ret.Get(1).(func(sriracha.RawRecord, sriracha.FieldSet) error); ok {
		r1 = returnFunc(record, fs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenizer_TokenizeDeterministic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TokenizeDeterministic'
type MockTokenizer_TokenizeDeterministic_Call struct {
	*mock.Call
}

// TokenizeDeterministic is a helper method to define mock.On call
//   - record sriracha.RawRecord
//   - fs sriracha.FieldSet
func (_e *MockTokenizer_Expecter) TokenizeDeterministic(record interface{}, fs interface{}) *MockTokenizer_TokenizeDeterministic_Call {
	return &MockTokenizer_TokenizeDeterministic_Call{Call: _e.mock.On("TokenizeDeterministic", record, fs)}
}

func (_c *MockTokenizer_TokenizeDeterministic_Call) Run(run func(record sriracha.RawRecord, fs sriracha.FieldSet)) *MockTokenizer_TokenizeDeterministic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sriracha.RawRecord
		if args[0] != nil {
			arg0 = args[0].(sriracha.RawRecord)
		}
		var arg1 sriracha.FieldSet
		if args[1] != nil {
			arg1 = args[1].(sriracha.FieldSet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenizer_TokenizeDeterministic_Call) Return(deterministicToken sriracha.DeterministicToken, err error) *MockTokenizer_TokenizeDeterministic_Call {
	_c.Call.Return(deterministicToken, err)
	return _c
}

func (_c *MockTokenizer_TokenizeDeterministic_Call) RunAndReturn(run func(record sriracha.RawRecord, fs sriracha.FieldSet) (sriracha.DeterministicToken, error)) *MockTokenizer_TokenizeDeterministic_Call {
	_c.Call.Return(run)
	return _c
}

// TokenizeField provides a mock function for the type MockTokenizer
func (_mock *MockTokenizer) TokenizeField(value string, path sriracha.FieldPath) ([]byte, error) {
	ret := _mock.Called(value, path)

	if len(ret) == 0 {
		panic("no return value specified for TokenizeField")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, sriracha.FieldPath) ([]byte, error)); ok {
		return returnFunc(value, path)
	}
	if returnFunc, ok := ret.Get(0).(func(string, sriracha.FieldPath) []byte); ok {
		r0 = returnFunc(value, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, sriracha.FieldPath) error); ok {
		r1 = returnFunc(value, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenizer_TokenizeField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TokenizeField'
type MockTokenizer_TokenizeField_Call struct {
	*mock.Call
}

// TokenizeField is a helper method to define mock.On call
//   - value string
//   - path sriracha.FieldPath
func (_e *MockTokenizer_Expecter) TokenizeField(value interface{}, path interface{}) *MockTokenizer_TokenizeField_Call {
	return &MockTokenizer_TokenizeField_Call{Call: _e.mock.On("TokenizeField", value, path)}
}

func (_c *MockTokenizer_TokenizeField_Call) Run(run func(value string, path sriracha.FieldPath)) *MockTokenizer_TokenizeField_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 sriracha.FieldPath
		if args[1] != nil {
			arg1 = args[1].(sriracha.FieldPath)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenizer_TokenizeField_Call) Return(bytes []byte, err error) *MockTokenizer_TokenizeField_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockTokenizer_TokenizeField_Call) RunAndReturn(run func(value string, path sriracha.FieldPath) ([]byte, error)) *MockTokenizer_TokenizeField_Call {
	_c.Call.Return(run)
	return _c
}

// TokenizeProbabilistic provides a mock function for the type MockTokenizer
func (_mock *MockTokenizer) TokenizeProbabilistic(record sriracha.RawRecord, fs sriracha.FieldSet) (sriracha.ProbabilisticToken, error) {
	ret := _mock.Called(record, fs)

	if len(ret) == 0 {
		panic("no return value specified for TokenizeProbabilistic")
	}

	var r0 sriracha.ProbabilisticToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(sriracha.RawRecord, sriracha.FieldSet) (sriracha.ProbabilisticToken, error)); ok {
		return returnFunc(record, fs)
	}
	if returnFunc, ok := ret.Get(0).(func(sriracha.RawRecord, sriracha.FieldSet) sriracha.ProbabilisticToken); ok {
		r0 = returnFunc(record, fs)
	} else {
		r0 = ret.Get(0).(sriracha.ProbabilisticToken)
	}
	if returnFunc, ok := ret.Get(1).(func(sriracha.RawRecord, sriracha.FieldSet) error); ok {
		r1 = returnFunc(record, fs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenizer_TokenizeProbabilistic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TokenizeProbabilistic'
type MockTokenizer_TokenizeProbabilistic_Call struct {
	*mock.Call
}

// TokenizeProbabilistic is a helper method to define mock.On call
//   - record sriracha.RawRecord
//   - fs sriracha.FieldSet
func (_e *MockTokenizer_Expecter) TokenizeProbabilistic(record interface{}, fs interface{}) *MockTokenizer_TokenizeProbabilistic_Call {
	return &MockTokenizer_TokenizeProbabilistic_Call{Call: _e.mock.On("TokenizeProbabilistic", record, fs)}
}

func (_c *MockTokenizer_TokenizeProbabilistic_Call) Run(run func(record sriracha.RawRecord, fs sriracha.FieldSet)) *MockTokenizer_TokenizeProbabilistic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sriracha.RawRecord
		if args[0] != nil {
			arg0 = args[0].(sriracha.RawRecord)
		}
		var arg1 sriracha.FieldSet
		if args[1] != nil {
			arg1 = args[1].(sriracha.FieldSet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenizer_TokenizeProbabilistic_Call) Return(probabilisticToken sriracha.ProbabilisticToken, err error) *MockTokenizer_TokenizeProbabilistic_Call {
	_c.Call.Return(probabilisticToken, err)
	return _c
}

func (_c *MockTokenizer_TokenizeProbabilistic_Call) RunAndReturn(run func(record sriracha.RawRecord, fs sriracha.FieldSet) (sriracha.ProbabilisticToken, error)) *MockTokenizer_TokenizeProbabilistic_Call {
	_c.Call.Return(run)
	return _c
}
