// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockreplay

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// Claim provides a mock function with given fields: policyID, expiresAt
func (_m *MockCache) Claim(policyID string, expiresAt time.Time) bool {
	ret := _m.Called(policyID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Claim")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, time.Time) bool); ok {
		r0 = rf(policyID, expiresAt)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockCache_Claim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Claim'
type MockCache_Claim_Call struct {
	*mock.Call
}

// Claim is a helper method to define mock.On call
//   - policyID string
//   - expiresAt time.Time
func (_e *MockCache_Expecter) Claim(policyID interface{}, expiresAt interface{}) *MockCache_Claim_Call {
	return &MockCache_Claim_Call{Call: _e.mock.On("Claim", policyID, expiresAt)}
}

func (_c *MockCache_Claim_Call) Run(run func(policyID string, expiresAt time.Time)) *MockCache_Claim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Time))
	})
	return _c
}

func (_c *MockCache_Claim_Call) Return(_a0 bool) *MockCache_Claim_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_Claim_Call) RunAndReturn(run func(string, time.Time) bool) *MockCache_Claim_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
